/*
Email Validation API — Enterprise-grade Email Verification

Testing APIKeysAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mailsafepro

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/mailsafepro/mailsafepro-go"
)

func Test_mailsafepro_APIKeysAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test APIKeysAPIService CreateApiKeyApiKeysPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIKeysAPI.CreateApiKeyApiKeysPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService CreateApiKeyApiKeysPost_1", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIKeysAPI.CreateApiKeyApiKeysPost_0(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService ForceSyncApiKeysForceSyncPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIKeysAPI.ForceSyncApiKeysForceSyncPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService ForceSyncApiKeysForceSyncPost_2", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIKeysAPI.ForceSyncApiKeysForceSyncPost_0(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService GetApiKeyValueApiKeysKeyHashValueGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyHash string

		resp, httpRes, err := apiClient.APIKeysAPI.GetApiKeyValueApiKeysKeyHashValueGet(context.Background(), keyHash).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService GetApiKeyValueApiKeysKeyHashValueGet_3", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyHash string

		resp, httpRes, err := apiClient.APIKeysAPI.GetApiKeyValueApiKeysKeyHashValueGet_0(context.Background(), keyHash).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService GetUsageApiKeysUsageGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIKeysAPI.GetUsageApiKeysUsageGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService GetUsageApiKeysUsageGet_4", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIKeysAPI.GetUsageApiKeysUsageGet_0(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService ListApiKeysApiKeysGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIKeysAPI.ListApiKeysApiKeysGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService ListApiKeysApiKeysGet_5", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIKeysAPI.ListApiKeysApiKeysGet_0(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService RepairUserDataEndpointApiKeysRepairDataPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIKeysAPI.RepairUserDataEndpointApiKeysRepairDataPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService RepairUserDataEndpointApiKeysRepairDataPost_6", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIKeysAPI.RepairUserDataEndpointApiKeysRepairDataPost_0(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService RevokeApiKeyApiKeysKeyHashRevokeDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyHash string

		resp, httpRes, err := apiClient.APIKeysAPI.RevokeApiKeyApiKeysKeyHashRevokeDelete(context.Background(), keyHash).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService RevokeApiKeyApiKeysKeyHashRevokeDelete_7", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyHash string

		resp, httpRes, err := apiClient.APIKeysAPI.RevokeApiKeyApiKeysKeyHashRevokeDelete_0(context.Background(), keyHash).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService RotateApiKeyApiKeysKeyHashRotatePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyHash string

		resp, httpRes, err := apiClient.APIKeysAPI.RotateApiKeyApiKeysKeyHashRotatePost(context.Background(), keyHash).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService RotateApiKeyApiKeysKeyHashRotatePost_8", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var keyHash string

		resp, httpRes, err := apiClient.APIKeysAPI.RotateApiKeyApiKeysKeyHashRotatePost_0(context.Background(), keyHash).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService SyncPlanKeysApiKeysSyncPlanKeysPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIKeysAPI.SyncPlanKeysApiKeysSyncPlanKeysPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test APIKeysAPIService SyncPlanKeysApiKeysSyncPlanKeysPost_9", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.APIKeysAPI.SyncPlanKeysApiKeysSyncPlanKeysPost_0(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
