/*
Email Validation API — Enterprise-grade Email Verification

Testing WebhooksManagementAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package mailsafepro

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/mailsafepro/mailsafepro-go"
)

func Test_mailsafepro_WebhooksManagementAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WebhooksManagementAPIService CreateWebhookWebhooksManagementWebhooksPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WebhooksManagementAPI.CreateWebhookWebhooksManagementWebhooksPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksManagementAPIService DeleteWebhookWebhooksManagementWebhooksWebhookIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var webhookId string

		resp, httpRes, err := apiClient.WebhooksManagementAPI.DeleteWebhookWebhooksManagementWebhooksWebhookIdDelete(context.Background(), webhookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksManagementAPIService GetDeliveriesWebhooksManagementWebhooksWebhookIdDeliveriesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var webhookId string

		resp, httpRes, err := apiClient.WebhooksManagementAPI.GetDeliveriesWebhooksManagementWebhooksWebhookIdDeliveriesGet(context.Background(), webhookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksManagementAPIService GetWebhookWebhooksManagementWebhooksWebhookIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var webhookId string

		resp, httpRes, err := apiClient.WebhooksManagementAPI.GetWebhookWebhooksManagementWebhooksWebhookIdGet(context.Background(), webhookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksManagementAPIService ListWebhooksWebhooksManagementWebhooksGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WebhooksManagementAPI.ListWebhooksWebhooksManagementWebhooksGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksManagementAPIService TestWebhookWebhooksManagementWebhooksWebhookIdTestPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var webhookId string

		resp, httpRes, err := apiClient.WebhooksManagementAPI.TestWebhookWebhooksManagementWebhooksWebhookIdTestPost(context.Background(), webhookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WebhooksManagementAPIService UpdateWebhookWebhooksManagementWebhooksWebhookIdPatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var webhookId string

		resp, httpRes, err := apiClient.WebhooksManagementAPI.UpdateWebhookWebhooksManagementWebhooksWebhookIdPatch(context.Background(), webhookId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
