/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type AuthenticationAPI interface {

	/*
	AuthHealthCheckAuthHealthAuthGet Auth Health Check

	Health check para autenticación: Redis, JWT y hashing.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAuthHealthCheckAuthHealthAuthGetRequest
	*/
	AuthHealthCheckAuthHealthAuthGet(ctx context.Context) ApiAuthHealthCheckAuthHealthAuthGetRequest

	// AuthHealthCheckAuthHealthAuthGetExecute executes the request
	//  @return interface{}
	AuthHealthCheckAuthHealthAuthGetExecute(r ApiAuthHealthCheckAuthHealthAuthGetRequest) (interface{}, *http.Response, error)

	/*
	AuthHealthCheckAuthHealthAuthGet_0 Auth Health Check

	Health check para autenticación: Redis, JWT y hashing.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAuthHealthCheckAuthHealthAuthGet_0Request
	*/
	AuthHealthCheckAuthHealthAuthGet_1(ctx context.Context) ApiAuthHealthCheckAuthHealthAuthGet_0Request

	// AuthHealthCheckAuthHealthAuthGet_1Execute executes the request
	//  @return interface{}
	AuthHealthCheckAuthHealthAuthGet_1Execute(r ApiAuthHealthCheckAuthHealthAuthGet_0Request) (interface{}, *http.Response, error)

	/*
	AuthHealthCheckAuthHealthAuthHead Auth Health Check

	Health check para autenticación: Redis, JWT y hashing.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAuthHealthCheckAuthHealthAuthHeadRequest
	*/
	AuthHealthCheckAuthHealthAuthHead(ctx context.Context) ApiAuthHealthCheckAuthHealthAuthHeadRequest

	// AuthHealthCheckAuthHealthAuthHeadExecute executes the request
	//  @return interface{}
	AuthHealthCheckAuthHealthAuthHeadExecute(r ApiAuthHealthCheckAuthHealthAuthHeadRequest) (interface{}, *http.Response, error)

	/*
	AuthHealthCheckAuthHealthAuthHead_0 Auth Health Check

	Health check para autenticación: Redis, JWT y hashing.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAuthHealthCheckAuthHealthAuthHead_0Request
	*/
	AuthHealthCheckAuthHealthAuthHead_2(ctx context.Context) ApiAuthHealthCheckAuthHealthAuthHead_0Request

	// AuthHealthCheckAuthHealthAuthHead_2Execute executes the request
	//  @return interface{}
	AuthHealthCheckAuthHealthAuthHead_2Execute(r ApiAuthHealthCheckAuthHealthAuthHead_0Request) (interface{}, *http.Response, error)

	/*
	DeleteAccountAuthDeleteDelete Delete Account

	Elimina la cuenta del usuario autenticado y todos sus datos relacionados.

⚠️ ADVERTENCIA: Esta operación es IRREVERSIBLE.

Elimina:
- Datos del usuario
- Todas las API keys
- Usage/quota
- Suscripciones
- Rate limits
- Tokens relacionados

Security:
- Solo el usuario puede eliminarse a sí mismo (o admin)
- Requiere autenticación válida
- Registra la acción en logs para auditoría
- Rate limited para prevenir abuse

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiDeleteAccountAuthDeleteDeleteRequest
	*/
	DeleteAccountAuthDeleteDelete(ctx context.Context) ApiDeleteAccountAuthDeleteDeleteRequest

	// DeleteAccountAuthDeleteDeleteExecute executes the request
	//  @return interface{}
	DeleteAccountAuthDeleteDeleteExecute(r ApiDeleteAccountAuthDeleteDeleteRequest) (interface{}, *http.Response, error)

	/*
	DeleteAccountAuthDeleteDelete_0 Delete Account

	Elimina la cuenta del usuario autenticado y todos sus datos relacionados.

⚠️ ADVERTENCIA: Esta operación es IRREVERSIBLE.

Elimina:
- Datos del usuario
- Todas las API keys
- Usage/quota
- Suscripciones
- Rate limits
- Tokens relacionados

Security:
- Solo el usuario puede eliminarse a sí mismo (o admin)
- Requiere autenticación válida
- Registra la acción en logs para auditoría
- Rate limited para prevenir abuse

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiDeleteAccountAuthDeleteDelete_0Request
	*/
	DeleteAccountAuthDeleteDelete_3(ctx context.Context) ApiDeleteAccountAuthDeleteDelete_0Request

	// DeleteAccountAuthDeleteDelete_3Execute executes the request
	//  @return interface{}
	DeleteAccountAuthDeleteDelete_3Execute(r ApiDeleteAccountAuthDeleteDelete_0Request) (interface{}, *http.Response, error)

	/*
	GetCurrentUserAuthMeGet Get Current User

	Devuelve información básica del usuario actual.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetCurrentUserAuthMeGetRequest
	*/
	GetCurrentUserAuthMeGet(ctx context.Context) ApiGetCurrentUserAuthMeGetRequest

	// GetCurrentUserAuthMeGetExecute executes the request
	//  @return map[string]interface{}
	GetCurrentUserAuthMeGetExecute(r ApiGetCurrentUserAuthMeGetRequest) (map[string]interface{}, *http.Response, error)

	/*
	GetCurrentUserAuthMeGet_0 Get Current User

	Devuelve información básica del usuario actual.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetCurrentUserAuthMeGet_0Request
	*/
	GetCurrentUserAuthMeGet_4(ctx context.Context) ApiGetCurrentUserAuthMeGet_0Request

	// GetCurrentUserAuthMeGet_4Execute executes the request
	//  @return map[string]interface{}
	GetCurrentUserAuthMeGet_4Execute(r ApiGetCurrentUserAuthMeGet_0Request) (map[string]interface{}, *http.Response, error)

	/*
	LoginWebUserAuthLoginPost Login Web User

	Login de usuario para panel web.

Security features:
- Rate limiting por email + IP
- Timing attack protection
- Generic error messages
- PII masking en logs

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiLoginWebUserAuthLoginPostRequest
	*/
	LoginWebUserAuthLoginPost(ctx context.Context) ApiLoginWebUserAuthLoginPostRequest

	// LoginWebUserAuthLoginPostExecute executes the request
	//  @return map[string]interface{}
	LoginWebUserAuthLoginPostExecute(r ApiLoginWebUserAuthLoginPostRequest) (map[string]interface{}, *http.Response, error)

	/*
	LoginWebUserAuthLoginPost_0 Login Web User

	Login de usuario para panel web.

Security features:
- Rate limiting por email + IP
- Timing attack protection
- Generic error messages
- PII masking en logs

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiLoginWebUserAuthLoginPost_0Request
	*/
	LoginWebUserAuthLoginPost_5(ctx context.Context) ApiLoginWebUserAuthLoginPost_0Request

	// LoginWebUserAuthLoginPost_5Execute executes the request
	//  @return map[string]interface{}
	LoginWebUserAuthLoginPost_5Execute(r ApiLoginWebUserAuthLoginPost_0Request) (map[string]interface{}, *http.Response, error)

	/*
	LogoutAuthLogoutPost Logout

	Logout idempotente:
- Si el access token es válido, lo añade a la blacklist.
- Si el access token está expirado, responde 200 indicando que ya estaba expirado.
- Solo devuelve 401 si el token es completamente inválido (firma/claims corruptos).
- Intenta revocar el refresh token si se proporciona.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiLogoutAuthLogoutPostRequest
	*/
	LogoutAuthLogoutPost(ctx context.Context) ApiLogoutAuthLogoutPostRequest

	// LogoutAuthLogoutPostExecute executes the request
	//  @return interface{}
	LogoutAuthLogoutPostExecute(r ApiLogoutAuthLogoutPostRequest) (interface{}, *http.Response, error)

	/*
	LogoutAuthLogoutPost_0 Logout

	Logout idempotente:
- Si el access token es válido, lo añade a la blacklist.
- Si el access token está expirado, responde 200 indicando que ya estaba expirado.
- Solo devuelve 401 si el token es completamente inválido (firma/claims corruptos).
- Intenta revocar el refresh token si se proporciona.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiLogoutAuthLogoutPost_0Request
	*/
	LogoutAuthLogoutPost_6(ctx context.Context) ApiLogoutAuthLogoutPost_0Request

	// LogoutAuthLogoutPost_6Execute executes the request
	//  @return interface{}
	LogoutAuthLogoutPost_6Execute(r ApiLogoutAuthLogoutPost_0Request) (interface{}, *http.Response, error)

	/*
	RefreshTokenAuthRefreshPost Refresh Token

	Crea un nuevo par de tokens a partir de un refresh token válido y no revocado.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiRefreshTokenAuthRefreshPostRequest
	*/
	RefreshTokenAuthRefreshPost(ctx context.Context) ApiRefreshTokenAuthRefreshPostRequest

	// RefreshTokenAuthRefreshPostExecute executes the request
	//  @return map[string]interface{}
	RefreshTokenAuthRefreshPostExecute(r ApiRefreshTokenAuthRefreshPostRequest) (map[string]interface{}, *http.Response, error)

	/*
	RefreshTokenAuthRefreshPost_0 Refresh Token

	Crea un nuevo par de tokens a partir de un refresh token válido y no revocado.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiRefreshTokenAuthRefreshPost_0Request
	*/
	RefreshTokenAuthRefreshPost_7(ctx context.Context) ApiRefreshTokenAuthRefreshPost_0Request

	// RefreshTokenAuthRefreshPost_7Execute executes the request
	//  @return map[string]interface{}
	RefreshTokenAuthRefreshPost_7Execute(r ApiRefreshTokenAuthRefreshPost_0Request) (map[string]interface{}, *http.Response, error)

	/*
	RegisterWebUserAuthRegisterPost Register Web User

	Registro de usuario para panel web: crea usuario, API key y tokens.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiRegisterWebUserAuthRegisterPostRequest
	*/
	RegisterWebUserAuthRegisterPost(ctx context.Context) ApiRegisterWebUserAuthRegisterPostRequest

	// RegisterWebUserAuthRegisterPostExecute executes the request
	//  @return map[string]interface{}
	RegisterWebUserAuthRegisterPostExecute(r ApiRegisterWebUserAuthRegisterPostRequest) (map[string]interface{}, *http.Response, error)

	/*
	RegisterWebUserAuthRegisterPost_0 Register Web User

	Registro de usuario para panel web: crea usuario, API key y tokens.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiRegisterWebUserAuthRegisterPost_0Request
	*/
	RegisterWebUserAuthRegisterPost_8(ctx context.Context) ApiRegisterWebUserAuthRegisterPost_0Request

	// RegisterWebUserAuthRegisterPost_8Execute executes the request
	//  @return map[string]interface{}
	RegisterWebUserAuthRegisterPost_8Execute(r ApiRegisterWebUserAuthRegisterPost_0Request) (map[string]interface{}, *http.Response, error)

	/*
	RotateApiKeyAuthRotateKeyPost Rotate Api Key

	Rotación de API keys con período de gracia; acceso restringido a admin.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiRotateApiKeyAuthRotateKeyPostRequest
	*/
	RotateApiKeyAuthRotateKeyPost(ctx context.Context) ApiRotateApiKeyAuthRotateKeyPostRequest

	// RotateApiKeyAuthRotateKeyPostExecute executes the request
	//  @return map[string]interface{}
	RotateApiKeyAuthRotateKeyPostExecute(r ApiRotateApiKeyAuthRotateKeyPostRequest) (map[string]interface{}, *http.Response, error)

	/*
	RotateApiKeyAuthRotateKeyPost_0 Rotate Api Key

	Rotación de API keys con período de gracia; acceso restringido a admin.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiRotateApiKeyAuthRotateKeyPost_0Request
	*/
	RotateApiKeyAuthRotateKeyPost_9(ctx context.Context) ApiRotateApiKeyAuthRotateKeyPost_0Request

	// RotateApiKeyAuthRotateKeyPost_9Execute executes the request
	//  @return map[string]interface{}
	RotateApiKeyAuthRotateKeyPost_9Execute(r ApiRotateApiKeyAuthRotateKeyPost_0Request) (map[string]interface{}, *http.Response, error)
}

// AuthenticationAPIService AuthenticationAPI service
type AuthenticationAPIService service

type ApiAuthHealthCheckAuthHealthAuthGetRequest struct {
	ctx context.Context
	ApiService AuthenticationAPI
}

func (r ApiAuthHealthCheckAuthHealthAuthGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.AuthHealthCheckAuthHealthAuthGetExecute(r)
}

/*
AuthHealthCheckAuthHealthAuthGet Auth Health Check

Health check para autenticación: Redis, JWT y hashing.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAuthHealthCheckAuthHealthAuthGetRequest
*/
func (a *AuthenticationAPIService) AuthHealthCheckAuthHealthAuthGet(ctx context.Context) ApiAuthHealthCheckAuthHealthAuthGetRequest {
	return ApiAuthHealthCheckAuthHealthAuthGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AuthenticationAPIService) AuthHealthCheckAuthHealthAuthGetExecute(r ApiAuthHealthCheckAuthHealthAuthGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.AuthHealthCheckAuthHealthAuthGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/health/auth"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAuthHealthCheckAuthHealthAuthGet_0Request struct {
	ctx context.Context
	ApiService AuthenticationAPI
}

func (r ApiAuthHealthCheckAuthHealthAuthGet_0Request) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.AuthHealthCheckAuthHealthAuthGet_1Execute(r)
}

/*
AuthHealthCheckAuthHealthAuthGet_0 Auth Health Check

Health check para autenticación: Redis, JWT y hashing.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAuthHealthCheckAuthHealthAuthGet_0Request
*/
func (a *AuthenticationAPIService) AuthHealthCheckAuthHealthAuthGet_1(ctx context.Context) ApiAuthHealthCheckAuthHealthAuthGet_0Request {
	return ApiAuthHealthCheckAuthHealthAuthGet_0Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AuthenticationAPIService) AuthHealthCheckAuthHealthAuthGet_1Execute(r ApiAuthHealthCheckAuthHealthAuthGet_0Request) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.AuthHealthCheckAuthHealthAuthGet_1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/health/auth"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAuthHealthCheckAuthHealthAuthHeadRequest struct {
	ctx context.Context
	ApiService AuthenticationAPI
}

func (r ApiAuthHealthCheckAuthHealthAuthHeadRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.AuthHealthCheckAuthHealthAuthHeadExecute(r)
}

/*
AuthHealthCheckAuthHealthAuthHead Auth Health Check

Health check para autenticación: Redis, JWT y hashing.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAuthHealthCheckAuthHealthAuthHeadRequest
*/
func (a *AuthenticationAPIService) AuthHealthCheckAuthHealthAuthHead(ctx context.Context) ApiAuthHealthCheckAuthHealthAuthHeadRequest {
	return ApiAuthHealthCheckAuthHealthAuthHeadRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AuthenticationAPIService) AuthHealthCheckAuthHealthAuthHeadExecute(r ApiAuthHealthCheckAuthHealthAuthHeadRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodHead
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.AuthHealthCheckAuthHealthAuthHead")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/health/auth"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAuthHealthCheckAuthHealthAuthHead_0Request struct {
	ctx context.Context
	ApiService AuthenticationAPI
}

func (r ApiAuthHealthCheckAuthHealthAuthHead_0Request) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.AuthHealthCheckAuthHealthAuthHead_2Execute(r)
}

/*
AuthHealthCheckAuthHealthAuthHead_0 Auth Health Check

Health check para autenticación: Redis, JWT y hashing.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAuthHealthCheckAuthHealthAuthHead_0Request
*/
func (a *AuthenticationAPIService) AuthHealthCheckAuthHealthAuthHead_2(ctx context.Context) ApiAuthHealthCheckAuthHealthAuthHead_0Request {
	return ApiAuthHealthCheckAuthHealthAuthHead_0Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AuthenticationAPIService) AuthHealthCheckAuthHealthAuthHead_2Execute(r ApiAuthHealthCheckAuthHealthAuthHead_0Request) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodHead
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.AuthHealthCheckAuthHealthAuthHead_2")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/health/auth"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteAccountAuthDeleteDeleteRequest struct {
	ctx context.Context
	ApiService AuthenticationAPI
}

func (r ApiDeleteAccountAuthDeleteDeleteRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.DeleteAccountAuthDeleteDeleteExecute(r)
}

/*
DeleteAccountAuthDeleteDelete Delete Account

Elimina la cuenta del usuario autenticado y todos sus datos relacionados.

⚠️ ADVERTENCIA: Esta operación es IRREVERSIBLE.

Elimina:
- Datos del usuario
- Todas las API keys
- Usage/quota
- Suscripciones
- Rate limits
- Tokens relacionados

Security:
- Solo el usuario puede eliminarse a sí mismo (o admin)
- Requiere autenticación válida
- Registra la acción en logs para auditoría
- Rate limited para prevenir abuse

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiDeleteAccountAuthDeleteDeleteRequest
*/
func (a *AuthenticationAPIService) DeleteAccountAuthDeleteDelete(ctx context.Context) ApiDeleteAccountAuthDeleteDeleteRequest {
	return ApiDeleteAccountAuthDeleteDeleteRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AuthenticationAPIService) DeleteAccountAuthDeleteDeleteExecute(r ApiDeleteAccountAuthDeleteDeleteRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.DeleteAccountAuthDeleteDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/delete"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteAccountAuthDeleteDelete_0Request struct {
	ctx context.Context
	ApiService AuthenticationAPI
}

func (r ApiDeleteAccountAuthDeleteDelete_0Request) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.DeleteAccountAuthDeleteDelete_3Execute(r)
}

/*
DeleteAccountAuthDeleteDelete_0 Delete Account

Elimina la cuenta del usuario autenticado y todos sus datos relacionados.

⚠️ ADVERTENCIA: Esta operación es IRREVERSIBLE.

Elimina:
- Datos del usuario
- Todas las API keys
- Usage/quota
- Suscripciones
- Rate limits
- Tokens relacionados

Security:
- Solo el usuario puede eliminarse a sí mismo (o admin)
- Requiere autenticación válida
- Registra la acción en logs para auditoría
- Rate limited para prevenir abuse

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiDeleteAccountAuthDeleteDelete_0Request
*/
func (a *AuthenticationAPIService) DeleteAccountAuthDeleteDelete_3(ctx context.Context) ApiDeleteAccountAuthDeleteDelete_0Request {
	return ApiDeleteAccountAuthDeleteDelete_0Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AuthenticationAPIService) DeleteAccountAuthDeleteDelete_3Execute(r ApiDeleteAccountAuthDeleteDelete_0Request) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.DeleteAccountAuthDeleteDelete_3")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/delete"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetCurrentUserAuthMeGetRequest struct {
	ctx context.Context
	ApiService AuthenticationAPI
}

func (r ApiGetCurrentUserAuthMeGetRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.GetCurrentUserAuthMeGetExecute(r)
}

/*
GetCurrentUserAuthMeGet Get Current User

Devuelve información básica del usuario actual.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetCurrentUserAuthMeGetRequest
*/
func (a *AuthenticationAPIService) GetCurrentUserAuthMeGet(ctx context.Context) ApiGetCurrentUserAuthMeGetRequest {
	return ApiGetCurrentUserAuthMeGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *AuthenticationAPIService) GetCurrentUserAuthMeGetExecute(r ApiGetCurrentUserAuthMeGetRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.GetCurrentUserAuthMeGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/me"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetCurrentUserAuthMeGet_0Request struct {
	ctx context.Context
	ApiService AuthenticationAPI
}

func (r ApiGetCurrentUserAuthMeGet_0Request) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.GetCurrentUserAuthMeGet_4Execute(r)
}

/*
GetCurrentUserAuthMeGet_0 Get Current User

Devuelve información básica del usuario actual.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetCurrentUserAuthMeGet_0Request
*/
func (a *AuthenticationAPIService) GetCurrentUserAuthMeGet_4(ctx context.Context) ApiGetCurrentUserAuthMeGet_0Request {
	return ApiGetCurrentUserAuthMeGet_0Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *AuthenticationAPIService) GetCurrentUserAuthMeGet_4Execute(r ApiGetCurrentUserAuthMeGet_0Request) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.GetCurrentUserAuthMeGet_4")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/me"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiLoginWebUserAuthLoginPostRequest struct {
	ctx context.Context
	ApiService AuthenticationAPI
	userLogin *UserLogin
}

func (r ApiLoginWebUserAuthLoginPostRequest) UserLogin(userLogin UserLogin) ApiLoginWebUserAuthLoginPostRequest {
	r.userLogin = &userLogin
	return r
}

func (r ApiLoginWebUserAuthLoginPostRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.LoginWebUserAuthLoginPostExecute(r)
}

/*
LoginWebUserAuthLoginPost Login Web User

Login de usuario para panel web.

Security features:
- Rate limiting por email + IP
- Timing attack protection
- Generic error messages
- PII masking en logs

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiLoginWebUserAuthLoginPostRequest
*/
func (a *AuthenticationAPIService) LoginWebUserAuthLoginPost(ctx context.Context) ApiLoginWebUserAuthLoginPostRequest {
	return ApiLoginWebUserAuthLoginPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *AuthenticationAPIService) LoginWebUserAuthLoginPostExecute(r ApiLoginWebUserAuthLoginPostRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.LoginWebUserAuthLoginPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/login"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.userLogin == nil {
		return localVarReturnValue, nil, reportError("userLogin is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.userLogin
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiLoginWebUserAuthLoginPost_0Request struct {
	ctx context.Context
	ApiService AuthenticationAPI
	userLogin *UserLogin
}

func (r ApiLoginWebUserAuthLoginPost_0Request) UserLogin(userLogin UserLogin) ApiLoginWebUserAuthLoginPost_0Request {
	r.userLogin = &userLogin
	return r
}

func (r ApiLoginWebUserAuthLoginPost_0Request) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.LoginWebUserAuthLoginPost_5Execute(r)
}

/*
LoginWebUserAuthLoginPost_0 Login Web User

Login de usuario para panel web.

Security features:
- Rate limiting por email + IP
- Timing attack protection
- Generic error messages
- PII masking en logs

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiLoginWebUserAuthLoginPost_0Request
*/
func (a *AuthenticationAPIService) LoginWebUserAuthLoginPost_5(ctx context.Context) ApiLoginWebUserAuthLoginPost_0Request {
	return ApiLoginWebUserAuthLoginPost_0Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *AuthenticationAPIService) LoginWebUserAuthLoginPost_5Execute(r ApiLoginWebUserAuthLoginPost_0Request) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.LoginWebUserAuthLoginPost_5")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/login"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.userLogin == nil {
		return localVarReturnValue, nil, reportError("userLogin is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.userLogin
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiLogoutAuthLogoutPostRequest struct {
	ctx context.Context
	ApiService AuthenticationAPI
}

func (r ApiLogoutAuthLogoutPostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.LogoutAuthLogoutPostExecute(r)
}

/*
LogoutAuthLogoutPost Logout

Logout idempotente:
- Si el access token es válido, lo añade a la blacklist.
- Si el access token está expirado, responde 200 indicando que ya estaba expirado.
- Solo devuelve 401 si el token es completamente inválido (firma/claims corruptos).
- Intenta revocar el refresh token si se proporciona.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiLogoutAuthLogoutPostRequest
*/
func (a *AuthenticationAPIService) LogoutAuthLogoutPost(ctx context.Context) ApiLogoutAuthLogoutPostRequest {
	return ApiLogoutAuthLogoutPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AuthenticationAPIService) LogoutAuthLogoutPostExecute(r ApiLogoutAuthLogoutPostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.LogoutAuthLogoutPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/logout"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiLogoutAuthLogoutPost_0Request struct {
	ctx context.Context
	ApiService AuthenticationAPI
}

func (r ApiLogoutAuthLogoutPost_0Request) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.LogoutAuthLogoutPost_6Execute(r)
}

/*
LogoutAuthLogoutPost_0 Logout

Logout idempotente:
- Si el access token es válido, lo añade a la blacklist.
- Si el access token está expirado, responde 200 indicando que ya estaba expirado.
- Solo devuelve 401 si el token es completamente inválido (firma/claims corruptos).
- Intenta revocar el refresh token si se proporciona.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiLogoutAuthLogoutPost_0Request
*/
func (a *AuthenticationAPIService) LogoutAuthLogoutPost_6(ctx context.Context) ApiLogoutAuthLogoutPost_0Request {
	return ApiLogoutAuthLogoutPost_0Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *AuthenticationAPIService) LogoutAuthLogoutPost_6Execute(r ApiLogoutAuthLogoutPost_0Request) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.LogoutAuthLogoutPost_6")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/logout"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRefreshTokenAuthRefreshPostRequest struct {
	ctx context.Context
	ApiService AuthenticationAPI
}

func (r ApiRefreshTokenAuthRefreshPostRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.RefreshTokenAuthRefreshPostExecute(r)
}

/*
RefreshTokenAuthRefreshPost Refresh Token

Crea un nuevo par de tokens a partir de un refresh token válido y no revocado.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiRefreshTokenAuthRefreshPostRequest
*/
func (a *AuthenticationAPIService) RefreshTokenAuthRefreshPost(ctx context.Context) ApiRefreshTokenAuthRefreshPostRequest {
	return ApiRefreshTokenAuthRefreshPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *AuthenticationAPIService) RefreshTokenAuthRefreshPostExecute(r ApiRefreshTokenAuthRefreshPostRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.RefreshTokenAuthRefreshPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/refresh"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRefreshTokenAuthRefreshPost_0Request struct {
	ctx context.Context
	ApiService AuthenticationAPI
}

func (r ApiRefreshTokenAuthRefreshPost_0Request) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.RefreshTokenAuthRefreshPost_7Execute(r)
}

/*
RefreshTokenAuthRefreshPost_0 Refresh Token

Crea un nuevo par de tokens a partir de un refresh token válido y no revocado.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiRefreshTokenAuthRefreshPost_0Request
*/
func (a *AuthenticationAPIService) RefreshTokenAuthRefreshPost_7(ctx context.Context) ApiRefreshTokenAuthRefreshPost_0Request {
	return ApiRefreshTokenAuthRefreshPost_0Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *AuthenticationAPIService) RefreshTokenAuthRefreshPost_7Execute(r ApiRefreshTokenAuthRefreshPost_0Request) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.RefreshTokenAuthRefreshPost_7")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/refresh"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRegisterWebUserAuthRegisterPostRequest struct {
	ctx context.Context
	ApiService AuthenticationAPI
	userRegister *UserRegister
}

func (r ApiRegisterWebUserAuthRegisterPostRequest) UserRegister(userRegister UserRegister) ApiRegisterWebUserAuthRegisterPostRequest {
	r.userRegister = &userRegister
	return r
}

func (r ApiRegisterWebUserAuthRegisterPostRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.RegisterWebUserAuthRegisterPostExecute(r)
}

/*
RegisterWebUserAuthRegisterPost Register Web User

Registro de usuario para panel web: crea usuario, API key y tokens.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiRegisterWebUserAuthRegisterPostRequest
*/
func (a *AuthenticationAPIService) RegisterWebUserAuthRegisterPost(ctx context.Context) ApiRegisterWebUserAuthRegisterPostRequest {
	return ApiRegisterWebUserAuthRegisterPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *AuthenticationAPIService) RegisterWebUserAuthRegisterPostExecute(r ApiRegisterWebUserAuthRegisterPostRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.RegisterWebUserAuthRegisterPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/register"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.userRegister == nil {
		return localVarReturnValue, nil, reportError("userRegister is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.userRegister
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRegisterWebUserAuthRegisterPost_0Request struct {
	ctx context.Context
	ApiService AuthenticationAPI
	userRegister *UserRegister
}

func (r ApiRegisterWebUserAuthRegisterPost_0Request) UserRegister(userRegister UserRegister) ApiRegisterWebUserAuthRegisterPost_0Request {
	r.userRegister = &userRegister
	return r
}

func (r ApiRegisterWebUserAuthRegisterPost_0Request) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.RegisterWebUserAuthRegisterPost_8Execute(r)
}

/*
RegisterWebUserAuthRegisterPost_0 Register Web User

Registro de usuario para panel web: crea usuario, API key y tokens.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiRegisterWebUserAuthRegisterPost_0Request
*/
func (a *AuthenticationAPIService) RegisterWebUserAuthRegisterPost_8(ctx context.Context) ApiRegisterWebUserAuthRegisterPost_0Request {
	return ApiRegisterWebUserAuthRegisterPost_0Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *AuthenticationAPIService) RegisterWebUserAuthRegisterPost_8Execute(r ApiRegisterWebUserAuthRegisterPost_0Request) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.RegisterWebUserAuthRegisterPost_8")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/register"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.userRegister == nil {
		return localVarReturnValue, nil, reportError("userRegister is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.userRegister
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRotateApiKeyAuthRotateKeyPostRequest struct {
	ctx context.Context
	ApiService AuthenticationAPI
	keyRotationRequest *KeyRotationRequest
}

func (r ApiRotateApiKeyAuthRotateKeyPostRequest) KeyRotationRequest(keyRotationRequest KeyRotationRequest) ApiRotateApiKeyAuthRotateKeyPostRequest {
	r.keyRotationRequest = &keyRotationRequest
	return r
}

func (r ApiRotateApiKeyAuthRotateKeyPostRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.RotateApiKeyAuthRotateKeyPostExecute(r)
}

/*
RotateApiKeyAuthRotateKeyPost Rotate Api Key

Rotación de API keys con período de gracia; acceso restringido a admin.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiRotateApiKeyAuthRotateKeyPostRequest
*/
func (a *AuthenticationAPIService) RotateApiKeyAuthRotateKeyPost(ctx context.Context) ApiRotateApiKeyAuthRotateKeyPostRequest {
	return ApiRotateApiKeyAuthRotateKeyPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *AuthenticationAPIService) RotateApiKeyAuthRotateKeyPostExecute(r ApiRotateApiKeyAuthRotateKeyPostRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.RotateApiKeyAuthRotateKeyPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/rotate-key"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.keyRotationRequest == nil {
		return localVarReturnValue, nil, reportError("keyRotationRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.keyRotationRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRotateApiKeyAuthRotateKeyPost_0Request struct {
	ctx context.Context
	ApiService AuthenticationAPI
	keyRotationRequest *KeyRotationRequest
}

func (r ApiRotateApiKeyAuthRotateKeyPost_0Request) KeyRotationRequest(keyRotationRequest KeyRotationRequest) ApiRotateApiKeyAuthRotateKeyPost_0Request {
	r.keyRotationRequest = &keyRotationRequest
	return r
}

func (r ApiRotateApiKeyAuthRotateKeyPost_0Request) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.RotateApiKeyAuthRotateKeyPost_9Execute(r)
}

/*
RotateApiKeyAuthRotateKeyPost_0 Rotate Api Key

Rotación de API keys con período de gracia; acceso restringido a admin.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiRotateApiKeyAuthRotateKeyPost_0Request
*/
func (a *AuthenticationAPIService) RotateApiKeyAuthRotateKeyPost_9(ctx context.Context) ApiRotateApiKeyAuthRotateKeyPost_0Request {
	return ApiRotateApiKeyAuthRotateKeyPost_0Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *AuthenticationAPIService) RotateApiKeyAuthRotateKeyPost_9Execute(r ApiRotateApiKeyAuthRotateKeyPost_0Request) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthenticationAPIService.RotateApiKeyAuthRotateKeyPost_9")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/auth/rotate-key"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.keyRotationRequest == nil {
		return localVarReturnValue, nil, reportError("keyRotationRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.keyRotationRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
