/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://api.mailsafepro.es/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RotateSecret type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RotateSecret{}

// RotateSecret struct for RotateSecret
type RotateSecret struct {
	EndpointId string `json:"endpoint_id"`
}

type _RotateSecret RotateSecret

// NewRotateSecret instantiates a new RotateSecret object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotateSecret(endpointId string) *RotateSecret {
	this := RotateSecret{}
	this.EndpointId = endpointId
	return &this
}

// NewRotateSecretWithDefaults instantiates a new RotateSecret object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotateSecretWithDefaults() *RotateSecret {
	this := RotateSecret{}
	return &this
}

// GetEndpointId returns the EndpointId field value
func (o *RotateSecret) GetEndpointId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value
// and a boolean to check if the value has been set.
func (o *RotateSecret) GetEndpointIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointId, true
}

// SetEndpointId sets field value
func (o *RotateSecret) SetEndpointId(v string) {
	o.EndpointId = v
}

func (o RotateSecret) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RotateSecret) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["endpoint_id"] = o.EndpointId
	return toSerialize, nil
}

func (o *RotateSecret) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endpoint_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRotateSecret := _RotateSecret{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRotateSecret)

	if err != nil {
		return err
	}

	*o = RotateSecret(varRotateSecret)

	return err
}

type NullableRotateSecret struct {
	value *RotateSecret
	isSet bool
}

func (v NullableRotateSecret) Get() *RotateSecret {
	return v.value
}

func (v *NullableRotateSecret) Set(val *RotateSecret) {
	v.value = val
	v.isSet = true
}

func (v NullableRotateSecret) IsSet() bool {
	return v.isSet
}

func (v *NullableRotateSecret) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotateSecret(val *RotateSecret) *NullableRotateSecret {
	return &NullableRotateSecret{value: val, isSet: true}
}

func (v NullableRotateSecret) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotateSecret) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


