/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://api.mailsafepro.es/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmailValidationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailValidationRequest{}

// EmailValidationRequest Request model for single email validation
type EmailValidationRequest struct {
	// Email address to validate (RFC 5321 compliant)
	Email string `json:"email"`
	// Enable SMTP mailbox verification
	CheckSmtp *bool `json:"check_smtp,omitempty"`
	// Include raw DNS records
	IncludeRawDns *bool `json:"include_raw_dns,omitempty"`
	// Enable testing mode (allows special TLDs like .test, .example, etc.)
	TestingMode *bool `json:"testing_mode,omitempty"`
	// Validation priority level
	Priority *PriorityEnum `json:"priority,omitempty"`
}

type _EmailValidationRequest EmailValidationRequest

// NewEmailValidationRequest instantiates a new EmailValidationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailValidationRequest(email string) *EmailValidationRequest {
	this := EmailValidationRequest{}
	this.Email = email
	var checkSmtp bool = false
	this.CheckSmtp = &checkSmtp
	var includeRawDns bool = false
	this.IncludeRawDns = &includeRawDns
	var testingMode bool = false
	this.TestingMode = &testingMode
	var priority PriorityEnum = STANDARD
	this.Priority = &priority
	return &this
}

// NewEmailValidationRequestWithDefaults instantiates a new EmailValidationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailValidationRequestWithDefaults() *EmailValidationRequest {
	this := EmailValidationRequest{}
	var checkSmtp bool = false
	this.CheckSmtp = &checkSmtp
	var includeRawDns bool = false
	this.IncludeRawDns = &includeRawDns
	var testingMode bool = false
	this.TestingMode = &testingMode
	var priority PriorityEnum = STANDARD
	this.Priority = &priority
	return &this
}

// GetEmail returns the Email field value
func (o *EmailValidationRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *EmailValidationRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *EmailValidationRequest) SetEmail(v string) {
	o.Email = v
}

// GetCheckSmtp returns the CheckSmtp field value if set, zero value otherwise.
func (o *EmailValidationRequest) GetCheckSmtp() bool {
	if o == nil || IsNil(o.CheckSmtp) {
		var ret bool
		return ret
	}
	return *o.CheckSmtp
}

// GetCheckSmtpOk returns a tuple with the CheckSmtp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailValidationRequest) GetCheckSmtpOk() (*bool, bool) {
	if o == nil || IsNil(o.CheckSmtp) {
		return nil, false
	}
	return o.CheckSmtp, true
}

// HasCheckSmtp returns a boolean if a field has been set.
func (o *EmailValidationRequest) HasCheckSmtp() bool {
	if o != nil && !IsNil(o.CheckSmtp) {
		return true
	}

	return false
}

// SetCheckSmtp gets a reference to the given bool and assigns it to the CheckSmtp field.
func (o *EmailValidationRequest) SetCheckSmtp(v bool) {
	o.CheckSmtp = &v
}

// GetIncludeRawDns returns the IncludeRawDns field value if set, zero value otherwise.
func (o *EmailValidationRequest) GetIncludeRawDns() bool {
	if o == nil || IsNil(o.IncludeRawDns) {
		var ret bool
		return ret
	}
	return *o.IncludeRawDns
}

// GetIncludeRawDnsOk returns a tuple with the IncludeRawDns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailValidationRequest) GetIncludeRawDnsOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeRawDns) {
		return nil, false
	}
	return o.IncludeRawDns, true
}

// HasIncludeRawDns returns a boolean if a field has been set.
func (o *EmailValidationRequest) HasIncludeRawDns() bool {
	if o != nil && !IsNil(o.IncludeRawDns) {
		return true
	}

	return false
}

// SetIncludeRawDns gets a reference to the given bool and assigns it to the IncludeRawDns field.
func (o *EmailValidationRequest) SetIncludeRawDns(v bool) {
	o.IncludeRawDns = &v
}

// GetTestingMode returns the TestingMode field value if set, zero value otherwise.
func (o *EmailValidationRequest) GetTestingMode() bool {
	if o == nil || IsNil(o.TestingMode) {
		var ret bool
		return ret
	}
	return *o.TestingMode
}

// GetTestingModeOk returns a tuple with the TestingMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailValidationRequest) GetTestingModeOk() (*bool, bool) {
	if o == nil || IsNil(o.TestingMode) {
		return nil, false
	}
	return o.TestingMode, true
}

// HasTestingMode returns a boolean if a field has been set.
func (o *EmailValidationRequest) HasTestingMode() bool {
	if o != nil && !IsNil(o.TestingMode) {
		return true
	}

	return false
}

// SetTestingMode gets a reference to the given bool and assigns it to the TestingMode field.
func (o *EmailValidationRequest) SetTestingMode(v bool) {
	o.TestingMode = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *EmailValidationRequest) GetPriority() PriorityEnum {
	if o == nil || IsNil(o.Priority) {
		var ret PriorityEnum
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailValidationRequest) GetPriorityOk() (*PriorityEnum, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *EmailValidationRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given PriorityEnum and assigns it to the Priority field.
func (o *EmailValidationRequest) SetPriority(v PriorityEnum) {
	o.Priority = &v
}

func (o EmailValidationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailValidationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if !IsNil(o.CheckSmtp) {
		toSerialize["check_smtp"] = o.CheckSmtp
	}
	if !IsNil(o.IncludeRawDns) {
		toSerialize["include_raw_dns"] = o.IncludeRawDns
	}
	if !IsNil(o.TestingMode) {
		toSerialize["testing_mode"] = o.TestingMode
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	return toSerialize, nil
}

func (o *EmailValidationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailValidationRequest := _EmailValidationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailValidationRequest)

	if err != nil {
		return err
	}

	*o = EmailValidationRequest(varEmailValidationRequest)

	return err
}

type NullableEmailValidationRequest struct {
	value *EmailValidationRequest
	isSet bool
}

func (v NullableEmailValidationRequest) Get() *EmailValidationRequest {
	return v.value
}

func (v *NullableEmailValidationRequest) Set(val *EmailValidationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailValidationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailValidationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailValidationRequest(val *EmailValidationRequest) *NullableEmailValidationRequest {
	return &NullableEmailValidationRequest{value: val, isSet: true}
}

func (v NullableEmailValidationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailValidationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


