/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BodyChangePlanBillingBillingChangePlanPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BodyChangePlanBillingBillingChangePlanPost{}

// BodyChangePlanBillingBillingChangePlanPost struct for BodyChangePlanBillingBillingChangePlanPost
type BodyChangePlanBillingBillingChangePlanPost struct {
	Plan string `json:"plan"`
}

type _BodyChangePlanBillingBillingChangePlanPost BodyChangePlanBillingBillingChangePlanPost

// NewBodyChangePlanBillingBillingChangePlanPost instantiates a new BodyChangePlanBillingBillingChangePlanPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBodyChangePlanBillingBillingChangePlanPost(plan string) *BodyChangePlanBillingBillingChangePlanPost {
	this := BodyChangePlanBillingBillingChangePlanPost{}
	this.Plan = plan
	return &this
}

// NewBodyChangePlanBillingBillingChangePlanPostWithDefaults instantiates a new BodyChangePlanBillingBillingChangePlanPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBodyChangePlanBillingBillingChangePlanPostWithDefaults() *BodyChangePlanBillingBillingChangePlanPost {
	this := BodyChangePlanBillingBillingChangePlanPost{}
	return &this
}

// GetPlan returns the Plan field value
func (o *BodyChangePlanBillingBillingChangePlanPost) GetPlan() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *BodyChangePlanBillingBillingChangePlanPost) GetPlanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *BodyChangePlanBillingBillingChangePlanPost) SetPlan(v string) {
	o.Plan = v
}

func (o BodyChangePlanBillingBillingChangePlanPost) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BodyChangePlanBillingBillingChangePlanPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plan"] = o.Plan
	return toSerialize, nil
}

func (o *BodyChangePlanBillingBillingChangePlanPost) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plan",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBodyChangePlanBillingBillingChangePlanPost := _BodyChangePlanBillingBillingChangePlanPost{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBodyChangePlanBillingBillingChangePlanPost)

	if err != nil {
		return err
	}

	*o = BodyChangePlanBillingBillingChangePlanPost(varBodyChangePlanBillingBillingChangePlanPost)

	return err
}

type NullableBodyChangePlanBillingBillingChangePlanPost struct {
	value *BodyChangePlanBillingBillingChangePlanPost
	isSet bool
}

func (v NullableBodyChangePlanBillingBillingChangePlanPost) Get() *BodyChangePlanBillingBillingChangePlanPost {
	return v.value
}

func (v *NullableBodyChangePlanBillingBillingChangePlanPost) Set(val *BodyChangePlanBillingBillingChangePlanPost) {
	v.value = val
	v.isSet = true
}

func (v NullableBodyChangePlanBillingBillingChangePlanPost) IsSet() bool {
	return v.isSet
}

func (v *NullableBodyChangePlanBillingBillingChangePlanPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBodyChangePlanBillingBillingChangePlanPost(val *BodyChangePlanBillingBillingChangePlanPost) *NullableBodyChangePlanBillingBillingChangePlanPost {
	return &NullableBodyChangePlanBillingBillingChangePlanPost{value: val, isSet: true}
}

func (v NullableBodyChangePlanBillingBillingChangePlanPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBodyChangePlanBillingBillingChangePlanPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


