/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://api.mailsafepro.es/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserRegister type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserRegister{}

// UserRegister User registration request
type UserRegister struct {
	// User email address
	Email string `json:"email"`
	// User password
	Password string `json:"password"`
	// Subscription plan
	Plan *PlanEnum `json:"plan,omitempty"`
}

type _UserRegister UserRegister

// NewUserRegister instantiates a new UserRegister object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserRegister(email string, password string) *UserRegister {
	this := UserRegister{}
	this.Email = email
	this.Password = password
	var plan PlanEnum = FREE
	this.Plan = &plan
	return &this
}

// NewUserRegisterWithDefaults instantiates a new UserRegister object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserRegisterWithDefaults() *UserRegister {
	this := UserRegister{}
	var plan PlanEnum = FREE
	this.Plan = &plan
	return &this
}

// GetEmail returns the Email field value
func (o *UserRegister) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UserRegister) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UserRegister) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *UserRegister) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *UserRegister) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *UserRegister) SetPassword(v string) {
	o.Password = v
}

// GetPlan returns the Plan field value if set, zero value otherwise.
func (o *UserRegister) GetPlan() PlanEnum {
	if o == nil || IsNil(o.Plan) {
		var ret PlanEnum
		return ret
	}
	return *o.Plan
}

// GetPlanOk returns a tuple with the Plan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserRegister) GetPlanOk() (*PlanEnum, bool) {
	if o == nil || IsNil(o.Plan) {
		return nil, false
	}
	return o.Plan, true
}

// HasPlan returns a boolean if a field has been set.
func (o *UserRegister) HasPlan() bool {
	if o != nil && !IsNil(o.Plan) {
		return true
	}

	return false
}

// SetPlan gets a reference to the given PlanEnum and assigns it to the Plan field.
func (o *UserRegister) SetPlan(v PlanEnum) {
	o.Plan = &v
}

func (o UserRegister) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserRegister) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password
	if !IsNil(o.Plan) {
		toSerialize["plan"] = o.Plan
	}
	return toSerialize, nil
}

func (o *UserRegister) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserRegister := _UserRegister{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserRegister)

	if err != nil {
		return err
	}

	*o = UserRegister(varUserRegister)

	return err
}

type NullableUserRegister struct {
	value *UserRegister
	isSet bool
}

func (v NullableUserRegister) Get() *UserRegister {
	return v.value
}

func (v *NullableUserRegister) Set(val *UserRegister) {
	v.value = val
	v.isSet = true
}

func (v NullableUserRegister) IsSet() bool {
	return v.isSet
}

func (v *NullableUserRegister) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserRegister(val *UserRegister) *NullableUserRegister {
	return &NullableUserRegister{value: val, isSet: true}
}

func (v NullableUserRegister) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserRegister) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


