/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchValidationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchValidationRequest{}

// BatchValidationRequest Request model for batch email validation
type BatchValidationRequest struct {
	// List of email addresses to validate (can include invalid formats)
	Emails []string `json:"emails"`
	// Perform SMTP verification for all emails
	CheckSmtp *bool `json:"check_smtp,omitempty"`
	// Include raw DNS records in responses
	IncludeRawDns *bool `json:"include_raw_dns,omitempty"`
	// Number of emails to process in each batch
	BatchSize *int32 `json:"batch_size,omitempty"`
	// Maximum concurrent validation requests
	ConcurrentRequests *int32 `json:"concurrent_requests,omitempty"`
}

type _BatchValidationRequest BatchValidationRequest

// NewBatchValidationRequest instantiates a new BatchValidationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchValidationRequest(emails []string) *BatchValidationRequest {
	this := BatchValidationRequest{}
	this.Emails = emails
	var checkSmtp bool = false
	this.CheckSmtp = &checkSmtp
	var includeRawDns bool = false
	this.IncludeRawDns = &includeRawDns
	var batchSize int32 = 100
	this.BatchSize = &batchSize
	var concurrentRequests int32 = 5
	this.ConcurrentRequests = &concurrentRequests
	return &this
}

// NewBatchValidationRequestWithDefaults instantiates a new BatchValidationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchValidationRequestWithDefaults() *BatchValidationRequest {
	this := BatchValidationRequest{}
	var checkSmtp bool = false
	this.CheckSmtp = &checkSmtp
	var includeRawDns bool = false
	this.IncludeRawDns = &includeRawDns
	var batchSize int32 = 100
	this.BatchSize = &batchSize
	var concurrentRequests int32 = 5
	this.ConcurrentRequests = &concurrentRequests
	return &this
}

// GetEmails returns the Emails field value
func (o *BatchValidationRequest) GetEmails() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value
// and a boolean to check if the value has been set.
func (o *BatchValidationRequest) GetEmailsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Emails, true
}

// SetEmails sets field value
func (o *BatchValidationRequest) SetEmails(v []string) {
	o.Emails = v
}

// GetCheckSmtp returns the CheckSmtp field value if set, zero value otherwise.
func (o *BatchValidationRequest) GetCheckSmtp() bool {
	if o == nil || IsNil(o.CheckSmtp) {
		var ret bool
		return ret
	}
	return *o.CheckSmtp
}

// GetCheckSmtpOk returns a tuple with the CheckSmtp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchValidationRequest) GetCheckSmtpOk() (*bool, bool) {
	if o == nil || IsNil(o.CheckSmtp) {
		return nil, false
	}
	return o.CheckSmtp, true
}

// HasCheckSmtp returns a boolean if a field has been set.
func (o *BatchValidationRequest) HasCheckSmtp() bool {
	if o != nil && !IsNil(o.CheckSmtp) {
		return true
	}

	return false
}

// SetCheckSmtp gets a reference to the given bool and assigns it to the CheckSmtp field.
func (o *BatchValidationRequest) SetCheckSmtp(v bool) {
	o.CheckSmtp = &v
}

// GetIncludeRawDns returns the IncludeRawDns field value if set, zero value otherwise.
func (o *BatchValidationRequest) GetIncludeRawDns() bool {
	if o == nil || IsNil(o.IncludeRawDns) {
		var ret bool
		return ret
	}
	return *o.IncludeRawDns
}

// GetIncludeRawDnsOk returns a tuple with the IncludeRawDns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchValidationRequest) GetIncludeRawDnsOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeRawDns) {
		return nil, false
	}
	return o.IncludeRawDns, true
}

// HasIncludeRawDns returns a boolean if a field has been set.
func (o *BatchValidationRequest) HasIncludeRawDns() bool {
	if o != nil && !IsNil(o.IncludeRawDns) {
		return true
	}

	return false
}

// SetIncludeRawDns gets a reference to the given bool and assigns it to the IncludeRawDns field.
func (o *BatchValidationRequest) SetIncludeRawDns(v bool) {
	o.IncludeRawDns = &v
}

// GetBatchSize returns the BatchSize field value if set, zero value otherwise.
func (o *BatchValidationRequest) GetBatchSize() int32 {
	if o == nil || IsNil(o.BatchSize) {
		var ret int32
		return ret
	}
	return *o.BatchSize
}

// GetBatchSizeOk returns a tuple with the BatchSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchValidationRequest) GetBatchSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.BatchSize) {
		return nil, false
	}
	return o.BatchSize, true
}

// HasBatchSize returns a boolean if a field has been set.
func (o *BatchValidationRequest) HasBatchSize() bool {
	if o != nil && !IsNil(o.BatchSize) {
		return true
	}

	return false
}

// SetBatchSize gets a reference to the given int32 and assigns it to the BatchSize field.
func (o *BatchValidationRequest) SetBatchSize(v int32) {
	o.BatchSize = &v
}

// GetConcurrentRequests returns the ConcurrentRequests field value if set, zero value otherwise.
func (o *BatchValidationRequest) GetConcurrentRequests() int32 {
	if o == nil || IsNil(o.ConcurrentRequests) {
		var ret int32
		return ret
	}
	return *o.ConcurrentRequests
}

// GetConcurrentRequestsOk returns a tuple with the ConcurrentRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchValidationRequest) GetConcurrentRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.ConcurrentRequests) {
		return nil, false
	}
	return o.ConcurrentRequests, true
}

// HasConcurrentRequests returns a boolean if a field has been set.
func (o *BatchValidationRequest) HasConcurrentRequests() bool {
	if o != nil && !IsNil(o.ConcurrentRequests) {
		return true
	}

	return false
}

// SetConcurrentRequests gets a reference to the given int32 and assigns it to the ConcurrentRequests field.
func (o *BatchValidationRequest) SetConcurrentRequests(v int32) {
	o.ConcurrentRequests = &v
}

func (o BatchValidationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchValidationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["emails"] = o.Emails
	if !IsNil(o.CheckSmtp) {
		toSerialize["check_smtp"] = o.CheckSmtp
	}
	if !IsNil(o.IncludeRawDns) {
		toSerialize["include_raw_dns"] = o.IncludeRawDns
	}
	if !IsNil(o.BatchSize) {
		toSerialize["batch_size"] = o.BatchSize
	}
	if !IsNil(o.ConcurrentRequests) {
		toSerialize["concurrent_requests"] = o.ConcurrentRequests
	}
	return toSerialize, nil
}

func (o *BatchValidationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"emails",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchValidationRequest := _BatchValidationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchValidationRequest)

	if err != nil {
		return err
	}

	*o = BatchValidationRequest(varBatchValidationRequest)

	return err
}

type NullableBatchValidationRequest struct {
	value *BatchValidationRequest
	isSet bool
}

func (v NullableBatchValidationRequest) Get() *BatchValidationRequest {
	return v.value
}

func (v *NullableBatchValidationRequest) Set(val *BatchValidationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchValidationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchValidationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchValidationRequest(val *BatchValidationRequest) *NullableBatchValidationRequest {
	return &NullableBatchValidationRequest{value: val, isSet: true}
}

func (v NullableBatchValidationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchValidationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


