/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobCreateResponse{}

// JobCreateResponse struct for JobCreateResponse
type JobCreateResponse struct {
	JobId string `json:"job_id"`
	Status string `json:"status"`
	CreatedAt string `json:"created_at"`
}

type _JobCreateResponse JobCreateResponse

// NewJobCreateResponse instantiates a new JobCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobCreateResponse(jobId string, status string, createdAt string) *JobCreateResponse {
	this := JobCreateResponse{}
	this.JobId = jobId
	this.Status = status
	this.CreatedAt = createdAt
	return &this
}

// NewJobCreateResponseWithDefaults instantiates a new JobCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobCreateResponseWithDefaults() *JobCreateResponse {
	this := JobCreateResponse{}
	return &this
}

// GetJobId returns the JobId field value
func (o *JobCreateResponse) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *JobCreateResponse) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *JobCreateResponse) SetJobId(v string) {
	o.JobId = v
}

// GetStatus returns the Status field value
func (o *JobCreateResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *JobCreateResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *JobCreateResponse) SetStatus(v string) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *JobCreateResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *JobCreateResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *JobCreateResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o JobCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job_id"] = o.JobId
	toSerialize["status"] = o.Status
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *JobCreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job_id",
		"status",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobCreateResponse := _JobCreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobCreateResponse)

	if err != nil {
		return err
	}

	*o = JobCreateResponse(varJobCreateResponse)

	return err
}

type NullableJobCreateResponse struct {
	value *JobCreateResponse
	isSet bool
}

func (v NullableJobCreateResponse) Get() *JobCreateResponse {
	return v.value
}

func (v *NullableJobCreateResponse) Set(val *JobCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableJobCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableJobCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobCreateResponse(val *JobCreateResponse) *NullableJobCreateResponse {
	return &NullableJobCreateResponse{value: val, isSet: true}
}

func (v NullableJobCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


