/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CheckoutSessionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckoutSessionResponse{}

// CheckoutSessionResponse Respuesta al crear checkout session.
type CheckoutSessionResponse struct {
	SessionId string `json:"session_id"`
}

type _CheckoutSessionResponse CheckoutSessionResponse

// NewCheckoutSessionResponse instantiates a new CheckoutSessionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckoutSessionResponse(sessionId string) *CheckoutSessionResponse {
	this := CheckoutSessionResponse{}
	this.SessionId = sessionId
	return &this
}

// NewCheckoutSessionResponseWithDefaults instantiates a new CheckoutSessionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckoutSessionResponseWithDefaults() *CheckoutSessionResponse {
	this := CheckoutSessionResponse{}
	return &this
}

// GetSessionId returns the SessionId field value
func (o *CheckoutSessionResponse) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *CheckoutSessionResponse) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *CheckoutSessionResponse) SetSessionId(v string) {
	o.SessionId = v
}

func (o CheckoutSessionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckoutSessionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["session_id"] = o.SessionId
	return toSerialize, nil
}

func (o *CheckoutSessionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"session_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckoutSessionResponse := _CheckoutSessionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckoutSessionResponse)

	if err != nil {
		return err
	}

	*o = CheckoutSessionResponse(varCheckoutSessionResponse)

	return err
}

type NullableCheckoutSessionResponse struct {
	value *CheckoutSessionResponse
	isSet bool
}

func (v NullableCheckoutSessionResponse) Get() *CheckoutSessionResponse {
	return v.value
}

func (v *NullableCheckoutSessionResponse) Set(val *CheckoutSessionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckoutSessionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckoutSessionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckoutSessionResponse(val *CheckoutSessionResponse) *NullableCheckoutSessionResponse {
	return &NullableCheckoutSessionResponse{value: val, isSet: true}
}

func (v NullableCheckoutSessionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckoutSessionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


