/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://api.mailsafepro.es/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
)

// checks if the DNSRecordSPF type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DNSRecordSPF{}

// DNSRecordSPF SPF DNS record information
type DNSRecordSPF struct {
	Status NullableString `json:"status,omitempty"`
	Record NullableString `json:"record,omitempty"`
	Mechanism NullableString `json:"mechanism,omitempty"`
	Domain NullableString `json:"domain,omitempty"`
}

// NewDNSRecordSPF instantiates a new DNSRecordSPF object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDNSRecordSPF() *DNSRecordSPF {
	this := DNSRecordSPF{}
	return &this
}

// NewDNSRecordSPFWithDefaults instantiates a new DNSRecordSPF object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDNSRecordSPFWithDefaults() *DNSRecordSPF {
	this := DNSRecordSPF{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DNSRecordSPF) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DNSRecordSPF) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *DNSRecordSPF) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *DNSRecordSPF) SetStatus(v string) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *DNSRecordSPF) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *DNSRecordSPF) UnsetStatus() {
	o.Status.Unset()
}

// GetRecord returns the Record field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DNSRecordSPF) GetRecord() string {
	if o == nil || IsNil(o.Record.Get()) {
		var ret string
		return ret
	}
	return *o.Record.Get()
}

// GetRecordOk returns a tuple with the Record field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DNSRecordSPF) GetRecordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Record.Get(), o.Record.IsSet()
}

// HasRecord returns a boolean if a field has been set.
func (o *DNSRecordSPF) HasRecord() bool {
	if o != nil && o.Record.IsSet() {
		return true
	}

	return false
}

// SetRecord gets a reference to the given NullableString and assigns it to the Record field.
func (o *DNSRecordSPF) SetRecord(v string) {
	o.Record.Set(&v)
}
// SetRecordNil sets the value for Record to be an explicit nil
func (o *DNSRecordSPF) SetRecordNil() {
	o.Record.Set(nil)
}

// UnsetRecord ensures that no value is present for Record, not even an explicit nil
func (o *DNSRecordSPF) UnsetRecord() {
	o.Record.Unset()
}

// GetMechanism returns the Mechanism field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DNSRecordSPF) GetMechanism() string {
	if o == nil || IsNil(o.Mechanism.Get()) {
		var ret string
		return ret
	}
	return *o.Mechanism.Get()
}

// GetMechanismOk returns a tuple with the Mechanism field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DNSRecordSPF) GetMechanismOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mechanism.Get(), o.Mechanism.IsSet()
}

// HasMechanism returns a boolean if a field has been set.
func (o *DNSRecordSPF) HasMechanism() bool {
	if o != nil && o.Mechanism.IsSet() {
		return true
	}

	return false
}

// SetMechanism gets a reference to the given NullableString and assigns it to the Mechanism field.
func (o *DNSRecordSPF) SetMechanism(v string) {
	o.Mechanism.Set(&v)
}
// SetMechanismNil sets the value for Mechanism to be an explicit nil
func (o *DNSRecordSPF) SetMechanismNil() {
	o.Mechanism.Set(nil)
}

// UnsetMechanism ensures that no value is present for Mechanism, not even an explicit nil
func (o *DNSRecordSPF) UnsetMechanism() {
	o.Mechanism.Unset()
}

// GetDomain returns the Domain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DNSRecordSPF) GetDomain() string {
	if o == nil || IsNil(o.Domain.Get()) {
		var ret string
		return ret
	}
	return *o.Domain.Get()
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DNSRecordSPF) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Domain.Get(), o.Domain.IsSet()
}

// HasDomain returns a boolean if a field has been set.
func (o *DNSRecordSPF) HasDomain() bool {
	if o != nil && o.Domain.IsSet() {
		return true
	}

	return false
}

// SetDomain gets a reference to the given NullableString and assigns it to the Domain field.
func (o *DNSRecordSPF) SetDomain(v string) {
	o.Domain.Set(&v)
}
// SetDomainNil sets the value for Domain to be an explicit nil
func (o *DNSRecordSPF) SetDomainNil() {
	o.Domain.Set(nil)
}

// UnsetDomain ensures that no value is present for Domain, not even an explicit nil
func (o *DNSRecordSPF) UnsetDomain() {
	o.Domain.Unset()
}

func (o DNSRecordSPF) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DNSRecordSPF) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.Record.IsSet() {
		toSerialize["record"] = o.Record.Get()
	}
	if o.Mechanism.IsSet() {
		toSerialize["mechanism"] = o.Mechanism.Get()
	}
	if o.Domain.IsSet() {
		toSerialize["domain"] = o.Domain.Get()
	}
	return toSerialize, nil
}

type NullableDNSRecordSPF struct {
	value *DNSRecordSPF
	isSet bool
}

func (v NullableDNSRecordSPF) Get() *DNSRecordSPF {
	return v.value
}

func (v *NullableDNSRecordSPF) Set(val *DNSRecordSPF) {
	v.value = val
	v.isSet = true
}

func (v NullableDNSRecordSPF) IsSet() bool {
	return v.isSet
}

func (v *NullableDNSRecordSPF) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDNSRecordSPF(val *DNSRecordSPF) *NullableDNSRecordSPF {
	return &NullableDNSRecordSPF{value: val, isSet: true}
}

func (v NullableDNSRecordSPF) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDNSRecordSPF) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


