/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmailResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailResponse{}

// EmailResponse Comprehensive email validation response
type EmailResponse struct {
	// Validated email address
	Email string `json:"email"`
	// Overall validation result
	Valid bool `json:"valid"`
	// Validation details summary
	Detail *string `json:"detail,omitempty"`
	ProcessingTime NullableFloat32 `json:"processing_time,omitempty"`
	Provider NullableString `json:"provider,omitempty"`
	Reputation NullableFloat32 `json:"reputation,omitempty"`
	Fingerprint NullableString `json:"fingerprint,omitempty"`
	QualityScore NullableFloat32 `json:"quality_score,omitempty"`
	RiskLevel NullableRiskLevelEnum `json:"risk_level,omitempty"`
	// Improvement suggestions
	Suggestions []string `json:"suggestions,omitempty"`
	Smtp NullableSMTPInfo `json:"smtp,omitempty"`
	Dns NullableDNSInfo `json:"dns,omitempty"`
	RiskScore NullableFloat32 `json:"risk_score,omitempty"`
	ValidationTier NullableString `json:"validation_tier,omitempty"`
	SuggestedAction NullableString `json:"suggested_action,omitempty"`
}

type _EmailResponse EmailResponse

// NewEmailResponse instantiates a new EmailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailResponse(email string, valid bool) *EmailResponse {
	this := EmailResponse{}
	this.Email = email
	this.Valid = valid
	var detail string = ""
	this.Detail = &detail
	return &this
}

// NewEmailResponseWithDefaults instantiates a new EmailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailResponseWithDefaults() *EmailResponse {
	this := EmailResponse{}
	var detail string = ""
	this.Detail = &detail
	return &this
}

// GetEmail returns the Email field value
func (o *EmailResponse) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *EmailResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *EmailResponse) SetEmail(v string) {
	o.Email = v
}

// GetValid returns the Valid field value
func (o *EmailResponse) GetValid() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Valid
}

// GetValidOk returns a tuple with the Valid field value
// and a boolean to check if the value has been set.
func (o *EmailResponse) GetValidOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Valid, true
}

// SetValid sets field value
func (o *EmailResponse) SetValid(v bool) {
	o.Valid = v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *EmailResponse) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailResponse) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *EmailResponse) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *EmailResponse) SetDetail(v string) {
	o.Detail = &v
}

// GetProcessingTime returns the ProcessingTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailResponse) GetProcessingTime() float32 {
	if o == nil || IsNil(o.ProcessingTime.Get()) {
		var ret float32
		return ret
	}
	return *o.ProcessingTime.Get()
}

// GetProcessingTimeOk returns a tuple with the ProcessingTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailResponse) GetProcessingTimeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProcessingTime.Get(), o.ProcessingTime.IsSet()
}

// HasProcessingTime returns a boolean if a field has been set.
func (o *EmailResponse) HasProcessingTime() bool {
	if o != nil && o.ProcessingTime.IsSet() {
		return true
	}

	return false
}

// SetProcessingTime gets a reference to the given NullableFloat32 and assigns it to the ProcessingTime field.
func (o *EmailResponse) SetProcessingTime(v float32) {
	o.ProcessingTime.Set(&v)
}
// SetProcessingTimeNil sets the value for ProcessingTime to be an explicit nil
func (o *EmailResponse) SetProcessingTimeNil() {
	o.ProcessingTime.Set(nil)
}

// UnsetProcessingTime ensures that no value is present for ProcessingTime, not even an explicit nil
func (o *EmailResponse) UnsetProcessingTime() {
	o.ProcessingTime.Unset()
}

// GetProvider returns the Provider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailResponse) GetProvider() string {
	if o == nil || IsNil(o.Provider.Get()) {
		var ret string
		return ret
	}
	return *o.Provider.Get()
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailResponse) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provider.Get(), o.Provider.IsSet()
}

// HasProvider returns a boolean if a field has been set.
func (o *EmailResponse) HasProvider() bool {
	if o != nil && o.Provider.IsSet() {
		return true
	}

	return false
}

// SetProvider gets a reference to the given NullableString and assigns it to the Provider field.
func (o *EmailResponse) SetProvider(v string) {
	o.Provider.Set(&v)
}
// SetProviderNil sets the value for Provider to be an explicit nil
func (o *EmailResponse) SetProviderNil() {
	o.Provider.Set(nil)
}

// UnsetProvider ensures that no value is present for Provider, not even an explicit nil
func (o *EmailResponse) UnsetProvider() {
	o.Provider.Unset()
}

// GetReputation returns the Reputation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailResponse) GetReputation() float32 {
	if o == nil || IsNil(o.Reputation.Get()) {
		var ret float32
		return ret
	}
	return *o.Reputation.Get()
}

// GetReputationOk returns a tuple with the Reputation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailResponse) GetReputationOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reputation.Get(), o.Reputation.IsSet()
}

// HasReputation returns a boolean if a field has been set.
func (o *EmailResponse) HasReputation() bool {
	if o != nil && o.Reputation.IsSet() {
		return true
	}

	return false
}

// SetReputation gets a reference to the given NullableFloat32 and assigns it to the Reputation field.
func (o *EmailResponse) SetReputation(v float32) {
	o.Reputation.Set(&v)
}
// SetReputationNil sets the value for Reputation to be an explicit nil
func (o *EmailResponse) SetReputationNil() {
	o.Reputation.Set(nil)
}

// UnsetReputation ensures that no value is present for Reputation, not even an explicit nil
func (o *EmailResponse) UnsetReputation() {
	o.Reputation.Unset()
}

// GetFingerprint returns the Fingerprint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailResponse) GetFingerprint() string {
	if o == nil || IsNil(o.Fingerprint.Get()) {
		var ret string
		return ret
	}
	return *o.Fingerprint.Get()
}

// GetFingerprintOk returns a tuple with the Fingerprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailResponse) GetFingerprintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fingerprint.Get(), o.Fingerprint.IsSet()
}

// HasFingerprint returns a boolean if a field has been set.
func (o *EmailResponse) HasFingerprint() bool {
	if o != nil && o.Fingerprint.IsSet() {
		return true
	}

	return false
}

// SetFingerprint gets a reference to the given NullableString and assigns it to the Fingerprint field.
func (o *EmailResponse) SetFingerprint(v string) {
	o.Fingerprint.Set(&v)
}
// SetFingerprintNil sets the value for Fingerprint to be an explicit nil
func (o *EmailResponse) SetFingerprintNil() {
	o.Fingerprint.Set(nil)
}

// UnsetFingerprint ensures that no value is present for Fingerprint, not even an explicit nil
func (o *EmailResponse) UnsetFingerprint() {
	o.Fingerprint.Unset()
}

// GetQualityScore returns the QualityScore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailResponse) GetQualityScore() float32 {
	if o == nil || IsNil(o.QualityScore.Get()) {
		var ret float32
		return ret
	}
	return *o.QualityScore.Get()
}

// GetQualityScoreOk returns a tuple with the QualityScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailResponse) GetQualityScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.QualityScore.Get(), o.QualityScore.IsSet()
}

// HasQualityScore returns a boolean if a field has been set.
func (o *EmailResponse) HasQualityScore() bool {
	if o != nil && o.QualityScore.IsSet() {
		return true
	}

	return false
}

// SetQualityScore gets a reference to the given NullableFloat32 and assigns it to the QualityScore field.
func (o *EmailResponse) SetQualityScore(v float32) {
	o.QualityScore.Set(&v)
}
// SetQualityScoreNil sets the value for QualityScore to be an explicit nil
func (o *EmailResponse) SetQualityScoreNil() {
	o.QualityScore.Set(nil)
}

// UnsetQualityScore ensures that no value is present for QualityScore, not even an explicit nil
func (o *EmailResponse) UnsetQualityScore() {
	o.QualityScore.Unset()
}

// GetRiskLevel returns the RiskLevel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailResponse) GetRiskLevel() RiskLevelEnum {
	if o == nil || IsNil(o.RiskLevel.Get()) {
		var ret RiskLevelEnum
		return ret
	}
	return *o.RiskLevel.Get()
}

// GetRiskLevelOk returns a tuple with the RiskLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailResponse) GetRiskLevelOk() (*RiskLevelEnum, bool) {
	if o == nil {
		return nil, false
	}
	return o.RiskLevel.Get(), o.RiskLevel.IsSet()
}

// HasRiskLevel returns a boolean if a field has been set.
func (o *EmailResponse) HasRiskLevel() bool {
	if o != nil && o.RiskLevel.IsSet() {
		return true
	}

	return false
}

// SetRiskLevel gets a reference to the given NullableRiskLevelEnum and assigns it to the RiskLevel field.
func (o *EmailResponse) SetRiskLevel(v RiskLevelEnum) {
	o.RiskLevel.Set(&v)
}
// SetRiskLevelNil sets the value for RiskLevel to be an explicit nil
func (o *EmailResponse) SetRiskLevelNil() {
	o.RiskLevel.Set(nil)
}

// UnsetRiskLevel ensures that no value is present for RiskLevel, not even an explicit nil
func (o *EmailResponse) UnsetRiskLevel() {
	o.RiskLevel.Unset()
}

// GetSuggestions returns the Suggestions field value if set, zero value otherwise.
func (o *EmailResponse) GetSuggestions() []string {
	if o == nil || IsNil(o.Suggestions) {
		var ret []string
		return ret
	}
	return o.Suggestions
}

// GetSuggestionsOk returns a tuple with the Suggestions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailResponse) GetSuggestionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Suggestions) {
		return nil, false
	}
	return o.Suggestions, true
}

// HasSuggestions returns a boolean if a field has been set.
func (o *EmailResponse) HasSuggestions() bool {
	if o != nil && !IsNil(o.Suggestions) {
		return true
	}

	return false
}

// SetSuggestions gets a reference to the given []string and assigns it to the Suggestions field.
func (o *EmailResponse) SetSuggestions(v []string) {
	o.Suggestions = v
}

// GetSmtp returns the Smtp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailResponse) GetSmtp() SMTPInfo {
	if o == nil || IsNil(o.Smtp.Get()) {
		var ret SMTPInfo
		return ret
	}
	return *o.Smtp.Get()
}

// GetSmtpOk returns a tuple with the Smtp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailResponse) GetSmtpOk() (*SMTPInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Smtp.Get(), o.Smtp.IsSet()
}

// HasSmtp returns a boolean if a field has been set.
func (o *EmailResponse) HasSmtp() bool {
	if o != nil && o.Smtp.IsSet() {
		return true
	}

	return false
}

// SetSmtp gets a reference to the given NullableSMTPInfo and assigns it to the Smtp field.
func (o *EmailResponse) SetSmtp(v SMTPInfo) {
	o.Smtp.Set(&v)
}
// SetSmtpNil sets the value for Smtp to be an explicit nil
func (o *EmailResponse) SetSmtpNil() {
	o.Smtp.Set(nil)
}

// UnsetSmtp ensures that no value is present for Smtp, not even an explicit nil
func (o *EmailResponse) UnsetSmtp() {
	o.Smtp.Unset()
}

// GetDns returns the Dns field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailResponse) GetDns() DNSInfo {
	if o == nil || IsNil(o.Dns.Get()) {
		var ret DNSInfo
		return ret
	}
	return *o.Dns.Get()
}

// GetDnsOk returns a tuple with the Dns field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailResponse) GetDnsOk() (*DNSInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dns.Get(), o.Dns.IsSet()
}

// HasDns returns a boolean if a field has been set.
func (o *EmailResponse) HasDns() bool {
	if o != nil && o.Dns.IsSet() {
		return true
	}

	return false
}

// SetDns gets a reference to the given NullableDNSInfo and assigns it to the Dns field.
func (o *EmailResponse) SetDns(v DNSInfo) {
	o.Dns.Set(&v)
}
// SetDnsNil sets the value for Dns to be an explicit nil
func (o *EmailResponse) SetDnsNil() {
	o.Dns.Set(nil)
}

// UnsetDns ensures that no value is present for Dns, not even an explicit nil
func (o *EmailResponse) UnsetDns() {
	o.Dns.Unset()
}

// GetRiskScore returns the RiskScore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailResponse) GetRiskScore() float32 {
	if o == nil || IsNil(o.RiskScore.Get()) {
		var ret float32
		return ret
	}
	return *o.RiskScore.Get()
}

// GetRiskScoreOk returns a tuple with the RiskScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailResponse) GetRiskScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RiskScore.Get(), o.RiskScore.IsSet()
}

// HasRiskScore returns a boolean if a field has been set.
func (o *EmailResponse) HasRiskScore() bool {
	if o != nil && o.RiskScore.IsSet() {
		return true
	}

	return false
}

// SetRiskScore gets a reference to the given NullableFloat32 and assigns it to the RiskScore field.
func (o *EmailResponse) SetRiskScore(v float32) {
	o.RiskScore.Set(&v)
}
// SetRiskScoreNil sets the value for RiskScore to be an explicit nil
func (o *EmailResponse) SetRiskScoreNil() {
	o.RiskScore.Set(nil)
}

// UnsetRiskScore ensures that no value is present for RiskScore, not even an explicit nil
func (o *EmailResponse) UnsetRiskScore() {
	o.RiskScore.Unset()
}

// GetValidationTier returns the ValidationTier field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailResponse) GetValidationTier() string {
	if o == nil || IsNil(o.ValidationTier.Get()) {
		var ret string
		return ret
	}
	return *o.ValidationTier.Get()
}

// GetValidationTierOk returns a tuple with the ValidationTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailResponse) GetValidationTierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValidationTier.Get(), o.ValidationTier.IsSet()
}

// HasValidationTier returns a boolean if a field has been set.
func (o *EmailResponse) HasValidationTier() bool {
	if o != nil && o.ValidationTier.IsSet() {
		return true
	}

	return false
}

// SetValidationTier gets a reference to the given NullableString and assigns it to the ValidationTier field.
func (o *EmailResponse) SetValidationTier(v string) {
	o.ValidationTier.Set(&v)
}
// SetValidationTierNil sets the value for ValidationTier to be an explicit nil
func (o *EmailResponse) SetValidationTierNil() {
	o.ValidationTier.Set(nil)
}

// UnsetValidationTier ensures that no value is present for ValidationTier, not even an explicit nil
func (o *EmailResponse) UnsetValidationTier() {
	o.ValidationTier.Unset()
}

// GetSuggestedAction returns the SuggestedAction field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailResponse) GetSuggestedAction() string {
	if o == nil || IsNil(o.SuggestedAction.Get()) {
		var ret string
		return ret
	}
	return *o.SuggestedAction.Get()
}

// GetSuggestedActionOk returns a tuple with the SuggestedAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailResponse) GetSuggestedActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SuggestedAction.Get(), o.SuggestedAction.IsSet()
}

// HasSuggestedAction returns a boolean if a field has been set.
func (o *EmailResponse) HasSuggestedAction() bool {
	if o != nil && o.SuggestedAction.IsSet() {
		return true
	}

	return false
}

// SetSuggestedAction gets a reference to the given NullableString and assigns it to the SuggestedAction field.
func (o *EmailResponse) SetSuggestedAction(v string) {
	o.SuggestedAction.Set(&v)
}
// SetSuggestedActionNil sets the value for SuggestedAction to be an explicit nil
func (o *EmailResponse) SetSuggestedActionNil() {
	o.SuggestedAction.Set(nil)
}

// UnsetSuggestedAction ensures that no value is present for SuggestedAction, not even an explicit nil
func (o *EmailResponse) UnsetSuggestedAction() {
	o.SuggestedAction.Unset()
}

func (o EmailResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["valid"] = o.Valid
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if o.ProcessingTime.IsSet() {
		toSerialize["processing_time"] = o.ProcessingTime.Get()
	}
	if o.Provider.IsSet() {
		toSerialize["provider"] = o.Provider.Get()
	}
	if o.Reputation.IsSet() {
		toSerialize["reputation"] = o.Reputation.Get()
	}
	if o.Fingerprint.IsSet() {
		toSerialize["fingerprint"] = o.Fingerprint.Get()
	}
	if o.QualityScore.IsSet() {
		toSerialize["quality_score"] = o.QualityScore.Get()
	}
	if o.RiskLevel.IsSet() {
		toSerialize["risk_level"] = o.RiskLevel.Get()
	}
	if !IsNil(o.Suggestions) {
		toSerialize["suggestions"] = o.Suggestions
	}
	if o.Smtp.IsSet() {
		toSerialize["smtp"] = o.Smtp.Get()
	}
	if o.Dns.IsSet() {
		toSerialize["dns"] = o.Dns.Get()
	}
	if o.RiskScore.IsSet() {
		toSerialize["risk_score"] = o.RiskScore.Get()
	}
	if o.ValidationTier.IsSet() {
		toSerialize["validation_tier"] = o.ValidationTier.Get()
	}
	if o.SuggestedAction.IsSet() {
		toSerialize["suggested_action"] = o.SuggestedAction.Get()
	}
	return toSerialize, nil
}

func (o *EmailResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"valid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailResponse := _EmailResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailResponse)

	if err != nil {
		return err
	}

	*o = EmailResponse(varEmailResponse)

	return err
}

type NullableEmailResponse struct {
	value *EmailResponse
	isSet bool
}

func (v NullableEmailResponse) Get() *EmailResponse {
	return v.value
}

func (v *NullableEmailResponse) Set(val *EmailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailResponse(val *EmailResponse) *NullableEmailResponse {
	return &NullableEmailResponse{value: val, isSet: true}
}

func (v NullableEmailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


