/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://api.mailsafepro.es/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
)

// checks if the DNSInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DNSInfo{}

// DNSInfo Comprehensive DNS information for email validation
type DNSInfo struct {
	Spf NullableDNSRecordSPF `json:"spf,omitempty"`
	Dkim NullableDNSRecordDKIM `json:"dkim,omitempty"`
	Dmarc NullableDNSRecordDMARC `json:"dmarc,omitempty"`
	// MX records
	MxRecords []string `json:"mx_records,omitempty"`
	// Name servers
	NsRecords []string `json:"ns_records,omitempty"`
}

// NewDNSInfo instantiates a new DNSInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDNSInfo() *DNSInfo {
	this := DNSInfo{}
	return &this
}

// NewDNSInfoWithDefaults instantiates a new DNSInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDNSInfoWithDefaults() *DNSInfo {
	this := DNSInfo{}
	return &this
}

// GetSpf returns the Spf field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DNSInfo) GetSpf() DNSRecordSPF {
	if o == nil || IsNil(o.Spf.Get()) {
		var ret DNSRecordSPF
		return ret
	}
	return *o.Spf.Get()
}

// GetSpfOk returns a tuple with the Spf field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DNSInfo) GetSpfOk() (*DNSRecordSPF, bool) {
	if o == nil {
		return nil, false
	}
	return o.Spf.Get(), o.Spf.IsSet()
}

// HasSpf returns a boolean if a field has been set.
func (o *DNSInfo) HasSpf() bool {
	if o != nil && o.Spf.IsSet() {
		return true
	}

	return false
}

// SetSpf gets a reference to the given NullableDNSRecordSPF and assigns it to the Spf field.
func (o *DNSInfo) SetSpf(v DNSRecordSPF) {
	o.Spf.Set(&v)
}
// SetSpfNil sets the value for Spf to be an explicit nil
func (o *DNSInfo) SetSpfNil() {
	o.Spf.Set(nil)
}

// UnsetSpf ensures that no value is present for Spf, not even an explicit nil
func (o *DNSInfo) UnsetSpf() {
	o.Spf.Unset()
}

// GetDkim returns the Dkim field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DNSInfo) GetDkim() DNSRecordDKIM {
	if o == nil || IsNil(o.Dkim.Get()) {
		var ret DNSRecordDKIM
		return ret
	}
	return *o.Dkim.Get()
}

// GetDkimOk returns a tuple with the Dkim field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DNSInfo) GetDkimOk() (*DNSRecordDKIM, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dkim.Get(), o.Dkim.IsSet()
}

// HasDkim returns a boolean if a field has been set.
func (o *DNSInfo) HasDkim() bool {
	if o != nil && o.Dkim.IsSet() {
		return true
	}

	return false
}

// SetDkim gets a reference to the given NullableDNSRecordDKIM and assigns it to the Dkim field.
func (o *DNSInfo) SetDkim(v DNSRecordDKIM) {
	o.Dkim.Set(&v)
}
// SetDkimNil sets the value for Dkim to be an explicit nil
func (o *DNSInfo) SetDkimNil() {
	o.Dkim.Set(nil)
}

// UnsetDkim ensures that no value is present for Dkim, not even an explicit nil
func (o *DNSInfo) UnsetDkim() {
	o.Dkim.Unset()
}

// GetDmarc returns the Dmarc field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DNSInfo) GetDmarc() DNSRecordDMARC {
	if o == nil || IsNil(o.Dmarc.Get()) {
		var ret DNSRecordDMARC
		return ret
	}
	return *o.Dmarc.Get()
}

// GetDmarcOk returns a tuple with the Dmarc field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DNSInfo) GetDmarcOk() (*DNSRecordDMARC, bool) {
	if o == nil {
		return nil, false
	}
	return o.Dmarc.Get(), o.Dmarc.IsSet()
}

// HasDmarc returns a boolean if a field has been set.
func (o *DNSInfo) HasDmarc() bool {
	if o != nil && o.Dmarc.IsSet() {
		return true
	}

	return false
}

// SetDmarc gets a reference to the given NullableDNSRecordDMARC and assigns it to the Dmarc field.
func (o *DNSInfo) SetDmarc(v DNSRecordDMARC) {
	o.Dmarc.Set(&v)
}
// SetDmarcNil sets the value for Dmarc to be an explicit nil
func (o *DNSInfo) SetDmarcNil() {
	o.Dmarc.Set(nil)
}

// UnsetDmarc ensures that no value is present for Dmarc, not even an explicit nil
func (o *DNSInfo) UnsetDmarc() {
	o.Dmarc.Unset()
}

// GetMxRecords returns the MxRecords field value if set, zero value otherwise.
func (o *DNSInfo) GetMxRecords() []string {
	if o == nil || IsNil(o.MxRecords) {
		var ret []string
		return ret
	}
	return o.MxRecords
}

// GetMxRecordsOk returns a tuple with the MxRecords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DNSInfo) GetMxRecordsOk() ([]string, bool) {
	if o == nil || IsNil(o.MxRecords) {
		return nil, false
	}
	return o.MxRecords, true
}

// HasMxRecords returns a boolean if a field has been set.
func (o *DNSInfo) HasMxRecords() bool {
	if o != nil && !IsNil(o.MxRecords) {
		return true
	}

	return false
}

// SetMxRecords gets a reference to the given []string and assigns it to the MxRecords field.
func (o *DNSInfo) SetMxRecords(v []string) {
	o.MxRecords = v
}

// GetNsRecords returns the NsRecords field value if set, zero value otherwise.
func (o *DNSInfo) GetNsRecords() []string {
	if o == nil || IsNil(o.NsRecords) {
		var ret []string
		return ret
	}
	return o.NsRecords
}

// GetNsRecordsOk returns a tuple with the NsRecords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DNSInfo) GetNsRecordsOk() ([]string, bool) {
	if o == nil || IsNil(o.NsRecords) {
		return nil, false
	}
	return o.NsRecords, true
}

// HasNsRecords returns a boolean if a field has been set.
func (o *DNSInfo) HasNsRecords() bool {
	if o != nil && !IsNil(o.NsRecords) {
		return true
	}

	return false
}

// SetNsRecords gets a reference to the given []string and assigns it to the NsRecords field.
func (o *DNSInfo) SetNsRecords(v []string) {
	o.NsRecords = v
}

func (o DNSInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DNSInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Spf.IsSet() {
		toSerialize["spf"] = o.Spf.Get()
	}
	if o.Dkim.IsSet() {
		toSerialize["dkim"] = o.Dkim.Get()
	}
	if o.Dmarc.IsSet() {
		toSerialize["dmarc"] = o.Dmarc.Get()
	}
	if !IsNil(o.MxRecords) {
		toSerialize["mx_records"] = o.MxRecords
	}
	if !IsNil(o.NsRecords) {
		toSerialize["ns_records"] = o.NsRecords
	}
	return toSerialize, nil
}

type NullableDNSInfo struct {
	value *DNSInfo
	isSet bool
}

func (v NullableDNSInfo) Get() *DNSInfo {
	return v.value
}

func (v *NullableDNSInfo) Set(val *DNSInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableDNSInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableDNSInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDNSInfo(val *DNSInfo) *NullableDNSInfo {
	return &NullableDNSInfo{value: val, isSet: true}
}

func (v NullableDNSInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDNSInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


