/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterEndpoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterEndpoint{}

// RegisterEndpoint struct for RegisterEndpoint
type RegisterEndpoint struct {
	CallbackUrl string `json:"callback_url"`
}

type _RegisterEndpoint RegisterEndpoint

// NewRegisterEndpoint instantiates a new RegisterEndpoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterEndpoint(callbackUrl string) *RegisterEndpoint {
	this := RegisterEndpoint{}
	this.CallbackUrl = callbackUrl
	return &this
}

// NewRegisterEndpointWithDefaults instantiates a new RegisterEndpoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterEndpointWithDefaults() *RegisterEndpoint {
	this := RegisterEndpoint{}
	return &this
}

// GetCallbackUrl returns the CallbackUrl field value
func (o *RegisterEndpoint) GetCallbackUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value
// and a boolean to check if the value has been set.
func (o *RegisterEndpoint) GetCallbackUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CallbackUrl, true
}

// SetCallbackUrl sets field value
func (o *RegisterEndpoint) SetCallbackUrl(v string) {
	o.CallbackUrl = v
}

func (o RegisterEndpoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterEndpoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["callback_url"] = o.CallbackUrl
	return toSerialize, nil
}

func (o *RegisterEndpoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"callback_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterEndpoint := _RegisterEndpoint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterEndpoint)

	if err != nil {
		return err
	}

	*o = RegisterEndpoint(varRegisterEndpoint)

	return err
}

type NullableRegisterEndpoint struct {
	value *RegisterEndpoint
	isSet bool
}

func (v NullableRegisterEndpoint) Get() *RegisterEndpoint {
	return v.value
}

func (v *NullableRegisterEndpoint) Set(val *RegisterEndpoint) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterEndpoint) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterEndpoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterEndpoint(val *RegisterEndpoint) *NullableRegisterEndpoint {
	return &NullableRegisterEndpoint{value: val, isSet: true}
}

func (v NullableRegisterEndpoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterEndpoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


