/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://api.mailsafepro.es/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
)

// checks if the DNSRecordDMARC type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DNSRecordDMARC{}

// DNSRecordDMARC DMARC DNS record information
type DNSRecordDMARC struct {
	Status NullableString `json:"status,omitempty"`
	Policy NullableString `json:"policy,omitempty"`
	Record NullableString `json:"record,omitempty"`
	Pct NullableInt32 `json:"pct,omitempty"`
}

// NewDNSRecordDMARC instantiates a new DNSRecordDMARC object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDNSRecordDMARC() *DNSRecordDMARC {
	this := DNSRecordDMARC{}
	return &this
}

// NewDNSRecordDMARCWithDefaults instantiates a new DNSRecordDMARC object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDNSRecordDMARCWithDefaults() *DNSRecordDMARC {
	this := DNSRecordDMARC{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DNSRecordDMARC) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DNSRecordDMARC) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *DNSRecordDMARC) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *DNSRecordDMARC) SetStatus(v string) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *DNSRecordDMARC) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *DNSRecordDMARC) UnsetStatus() {
	o.Status.Unset()
}

// GetPolicy returns the Policy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DNSRecordDMARC) GetPolicy() string {
	if o == nil || IsNil(o.Policy.Get()) {
		var ret string
		return ret
	}
	return *o.Policy.Get()
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DNSRecordDMARC) GetPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Policy.Get(), o.Policy.IsSet()
}

// HasPolicy returns a boolean if a field has been set.
func (o *DNSRecordDMARC) HasPolicy() bool {
	if o != nil && o.Policy.IsSet() {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given NullableString and assigns it to the Policy field.
func (o *DNSRecordDMARC) SetPolicy(v string) {
	o.Policy.Set(&v)
}
// SetPolicyNil sets the value for Policy to be an explicit nil
func (o *DNSRecordDMARC) SetPolicyNil() {
	o.Policy.Set(nil)
}

// UnsetPolicy ensures that no value is present for Policy, not even an explicit nil
func (o *DNSRecordDMARC) UnsetPolicy() {
	o.Policy.Unset()
}

// GetRecord returns the Record field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DNSRecordDMARC) GetRecord() string {
	if o == nil || IsNil(o.Record.Get()) {
		var ret string
		return ret
	}
	return *o.Record.Get()
}

// GetRecordOk returns a tuple with the Record field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DNSRecordDMARC) GetRecordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Record.Get(), o.Record.IsSet()
}

// HasRecord returns a boolean if a field has been set.
func (o *DNSRecordDMARC) HasRecord() bool {
	if o != nil && o.Record.IsSet() {
		return true
	}

	return false
}

// SetRecord gets a reference to the given NullableString and assigns it to the Record field.
func (o *DNSRecordDMARC) SetRecord(v string) {
	o.Record.Set(&v)
}
// SetRecordNil sets the value for Record to be an explicit nil
func (o *DNSRecordDMARC) SetRecordNil() {
	o.Record.Set(nil)
}

// UnsetRecord ensures that no value is present for Record, not even an explicit nil
func (o *DNSRecordDMARC) UnsetRecord() {
	o.Record.Unset()
}

// GetPct returns the Pct field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DNSRecordDMARC) GetPct() int32 {
	if o == nil || IsNil(o.Pct.Get()) {
		var ret int32
		return ret
	}
	return *o.Pct.Get()
}

// GetPctOk returns a tuple with the Pct field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DNSRecordDMARC) GetPctOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pct.Get(), o.Pct.IsSet()
}

// HasPct returns a boolean if a field has been set.
func (o *DNSRecordDMARC) HasPct() bool {
	if o != nil && o.Pct.IsSet() {
		return true
	}

	return false
}

// SetPct gets a reference to the given NullableInt32 and assigns it to the Pct field.
func (o *DNSRecordDMARC) SetPct(v int32) {
	o.Pct.Set(&v)
}
// SetPctNil sets the value for Pct to be an explicit nil
func (o *DNSRecordDMARC) SetPctNil() {
	o.Pct.Set(nil)
}

// UnsetPct ensures that no value is present for Pct, not even an explicit nil
func (o *DNSRecordDMARC) UnsetPct() {
	o.Pct.Unset()
}

func (o DNSRecordDMARC) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DNSRecordDMARC) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	if o.Policy.IsSet() {
		toSerialize["policy"] = o.Policy.Get()
	}
	if o.Record.IsSet() {
		toSerialize["record"] = o.Record.Get()
	}
	if o.Pct.IsSet() {
		toSerialize["pct"] = o.Pct.Get()
	}
	return toSerialize, nil
}

type NullableDNSRecordDMARC struct {
	value *DNSRecordDMARC
	isSet bool
}

func (v NullableDNSRecordDMARC) Get() *DNSRecordDMARC {
	return v.value
}

func (v *NullableDNSRecordDMARC) Set(val *DNSRecordDMARC) {
	v.value = val
	v.isSet = true
}

func (v NullableDNSRecordDMARC) IsSet() bool {
	return v.isSet
}

func (v *NullableDNSRecordDMARC) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDNSRecordDMARC(val *DNSRecordDMARC) *NullableDNSRecordDMARC {
	return &NullableDNSRecordDMARC{value: val, isSet: true}
}

func (v NullableDNSRecordDMARC) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDNSRecordDMARC) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


