/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
	"fmt"
)


// ResponseTestNotificationBillingBillingTestNotificationPostValue struct for ResponseTestNotificationBillingBillingTestNotificationPostValue
type ResponseTestNotificationBillingBillingTestNotificationPostValue struct {
	Bool *bool
	String *string
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *ResponseTestNotificationBillingBillingTestNotificationPostValue) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into Bool
	err = json.Unmarshal(data, &dst.Bool);
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			return nil // data stored in dst.Bool, return on the first match
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal JSON data into String
	err = json.Unmarshal(data, &dst.String);
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			return nil // data stored in dst.String, return on the first match
		}
	} else {
		dst.String = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(ResponseTestNotificationBillingBillingTestNotificationPostValue)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ResponseTestNotificationBillingBillingTestNotificationPostValue) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableResponseTestNotificationBillingBillingTestNotificationPostValue struct {
	value *ResponseTestNotificationBillingBillingTestNotificationPostValue
	isSet bool
}

func (v NullableResponseTestNotificationBillingBillingTestNotificationPostValue) Get() *ResponseTestNotificationBillingBillingTestNotificationPostValue {
	return v.value
}

func (v *NullableResponseTestNotificationBillingBillingTestNotificationPostValue) Set(val *ResponseTestNotificationBillingBillingTestNotificationPostValue) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseTestNotificationBillingBillingTestNotificationPostValue) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseTestNotificationBillingBillingTestNotificationPostValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseTestNotificationBillingBillingTestNotificationPostValue(val *ResponseTestNotificationBillingBillingTestNotificationPostValue) *NullableResponseTestNotificationBillingBillingTestNotificationPostValue {
	return &NullableResponseTestNotificationBillingBillingTestNotificationPostValue{value: val, isSet: true}
}

func (v NullableResponseTestNotificationBillingBillingTestNotificationPostValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseTestNotificationBillingBillingTestNotificationPostValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


