/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://api.mailsafepro.es/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobCreateRequest{}

// JobCreateRequest struct for JobCreateRequest
type JobCreateRequest struct {
	// Origen de los datos
	Source string `json:"source" validate:"regexp=^(list|upload)$"`
	Emails []string `json:"emails,omitempty"`
	FileToken NullableString `json:"file_token,omitempty"`
	Checksmtp *bool `json:"checksmtp,omitempty"`
	Includerawdns *bool `json:"includerawdns,omitempty"`
	CallbackUrl NullableString `json:"callback_url,omitempty"`
	Sandbox *bool `json:"sandbox,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _JobCreateRequest JobCreateRequest

// NewJobCreateRequest instantiates a new JobCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobCreateRequest(source string) *JobCreateRequest {
	this := JobCreateRequest{}
	this.Source = source
	var checksmtp bool = false
	this.Checksmtp = &checksmtp
	var includerawdns bool = false
	this.Includerawdns = &includerawdns
	var sandbox bool = false
	this.Sandbox = &sandbox
	return &this
}

// NewJobCreateRequestWithDefaults instantiates a new JobCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobCreateRequestWithDefaults() *JobCreateRequest {
	this := JobCreateRequest{}
	var checksmtp bool = false
	this.Checksmtp = &checksmtp
	var includerawdns bool = false
	this.Includerawdns = &includerawdns
	var sandbox bool = false
	this.Sandbox = &sandbox
	return &this
}

// GetSource returns the Source field value
func (o *JobCreateRequest) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *JobCreateRequest) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *JobCreateRequest) SetSource(v string) {
	o.Source = v
}

// GetEmails returns the Emails field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobCreateRequest) GetEmails() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobCreateRequest) GetEmailsOk() ([]string, bool) {
	if o == nil || IsNil(o.Emails) {
		return nil, false
	}
	return o.Emails, true
}

// HasEmails returns a boolean if a field has been set.
func (o *JobCreateRequest) HasEmails() bool {
	if o != nil && !IsNil(o.Emails) {
		return true
	}

	return false
}

// SetEmails gets a reference to the given []string and assigns it to the Emails field.
func (o *JobCreateRequest) SetEmails(v []string) {
	o.Emails = v
}

// GetFileToken returns the FileToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobCreateRequest) GetFileToken() string {
	if o == nil || IsNil(o.FileToken.Get()) {
		var ret string
		return ret
	}
	return *o.FileToken.Get()
}

// GetFileTokenOk returns a tuple with the FileToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobCreateRequest) GetFileTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FileToken.Get(), o.FileToken.IsSet()
}

// HasFileToken returns a boolean if a field has been set.
func (o *JobCreateRequest) HasFileToken() bool {
	if o != nil && o.FileToken.IsSet() {
		return true
	}

	return false
}

// SetFileToken gets a reference to the given NullableString and assigns it to the FileToken field.
func (o *JobCreateRequest) SetFileToken(v string) {
	o.FileToken.Set(&v)
}
// SetFileTokenNil sets the value for FileToken to be an explicit nil
func (o *JobCreateRequest) SetFileTokenNil() {
	o.FileToken.Set(nil)
}

// UnsetFileToken ensures that no value is present for FileToken, not even an explicit nil
func (o *JobCreateRequest) UnsetFileToken() {
	o.FileToken.Unset()
}

// GetChecksmtp returns the Checksmtp field value if set, zero value otherwise.
func (o *JobCreateRequest) GetChecksmtp() bool {
	if o == nil || IsNil(o.Checksmtp) {
		var ret bool
		return ret
	}
	return *o.Checksmtp
}

// GetChecksmtpOk returns a tuple with the Checksmtp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobCreateRequest) GetChecksmtpOk() (*bool, bool) {
	if o == nil || IsNil(o.Checksmtp) {
		return nil, false
	}
	return o.Checksmtp, true
}

// HasChecksmtp returns a boolean if a field has been set.
func (o *JobCreateRequest) HasChecksmtp() bool {
	if o != nil && !IsNil(o.Checksmtp) {
		return true
	}

	return false
}

// SetChecksmtp gets a reference to the given bool and assigns it to the Checksmtp field.
func (o *JobCreateRequest) SetChecksmtp(v bool) {
	o.Checksmtp = &v
}

// GetIncluderawdns returns the Includerawdns field value if set, zero value otherwise.
func (o *JobCreateRequest) GetIncluderawdns() bool {
	if o == nil || IsNil(o.Includerawdns) {
		var ret bool
		return ret
	}
	return *o.Includerawdns
}

// GetIncluderawdnsOk returns a tuple with the Includerawdns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobCreateRequest) GetIncluderawdnsOk() (*bool, bool) {
	if o == nil || IsNil(o.Includerawdns) {
		return nil, false
	}
	return o.Includerawdns, true
}

// HasIncluderawdns returns a boolean if a field has been set.
func (o *JobCreateRequest) HasIncluderawdns() bool {
	if o != nil && !IsNil(o.Includerawdns) {
		return true
	}

	return false
}

// SetIncluderawdns gets a reference to the given bool and assigns it to the Includerawdns field.
func (o *JobCreateRequest) SetIncluderawdns(v bool) {
	o.Includerawdns = &v
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobCreateRequest) GetCallbackUrl() string {
	if o == nil || IsNil(o.CallbackUrl.Get()) {
		var ret string
		return ret
	}
	return *o.CallbackUrl.Get()
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobCreateRequest) GetCallbackUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CallbackUrl.Get(), o.CallbackUrl.IsSet()
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *JobCreateRequest) HasCallbackUrl() bool {
	if o != nil && o.CallbackUrl.IsSet() {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given NullableString and assigns it to the CallbackUrl field.
func (o *JobCreateRequest) SetCallbackUrl(v string) {
	o.CallbackUrl.Set(&v)
}
// SetCallbackUrlNil sets the value for CallbackUrl to be an explicit nil
func (o *JobCreateRequest) SetCallbackUrlNil() {
	o.CallbackUrl.Set(nil)
}

// UnsetCallbackUrl ensures that no value is present for CallbackUrl, not even an explicit nil
func (o *JobCreateRequest) UnsetCallbackUrl() {
	o.CallbackUrl.Unset()
}

// GetSandbox returns the Sandbox field value if set, zero value otherwise.
func (o *JobCreateRequest) GetSandbox() bool {
	if o == nil || IsNil(o.Sandbox) {
		var ret bool
		return ret
	}
	return *o.Sandbox
}

// GetSandboxOk returns a tuple with the Sandbox field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobCreateRequest) GetSandboxOk() (*bool, bool) {
	if o == nil || IsNil(o.Sandbox) {
		return nil, false
	}
	return o.Sandbox, true
}

// HasSandbox returns a boolean if a field has been set.
func (o *JobCreateRequest) HasSandbox() bool {
	if o != nil && !IsNil(o.Sandbox) {
		return true
	}

	return false
}

// SetSandbox gets a reference to the given bool and assigns it to the Sandbox field.
func (o *JobCreateRequest) SetSandbox(v bool) {
	o.Sandbox = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JobCreateRequest) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobCreateRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *JobCreateRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *JobCreateRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o JobCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source"] = o.Source
	if o.Emails != nil {
		toSerialize["emails"] = o.Emails
	}
	if o.FileToken.IsSet() {
		toSerialize["file_token"] = o.FileToken.Get()
	}
	if !IsNil(o.Checksmtp) {
		toSerialize["checksmtp"] = o.Checksmtp
	}
	if !IsNil(o.Includerawdns) {
		toSerialize["includerawdns"] = o.Includerawdns
	}
	if o.CallbackUrl.IsSet() {
		toSerialize["callback_url"] = o.CallbackUrl.Get()
	}
	if !IsNil(o.Sandbox) {
		toSerialize["sandbox"] = o.Sandbox
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *JobCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobCreateRequest := _JobCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobCreateRequest)

	if err != nil {
		return err
	}

	*o = JobCreateRequest(varJobCreateRequest)

	return err
}

type NullableJobCreateRequest struct {
	value *JobCreateRequest
	isSet bool
}

func (v NullableJobCreateRequest) Get() *JobCreateRequest {
	return v.value
}

func (v *NullableJobCreateRequest) Set(val *JobCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableJobCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableJobCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobCreateRequest(val *JobCreateRequest) *NullableJobCreateRequest {
	return &NullableJobCreateRequest{value: val, isSet: true}
}

func (v NullableJobCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


