/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
	"fmt"
)

// RiskLevelEnum the model 'RiskLevelEnum'
type RiskLevelEnum string

// List of RiskLevelEnum
const (
	LOW RiskLevelEnum = "low"
	MEDIUM RiskLevelEnum = "medium"
	HIGH RiskLevelEnum = "high"
	UNKNOWN RiskLevelEnum = "unknown"
)

// All allowed values of RiskLevelEnum enum
var AllowedRiskLevelEnumEnumValues = []RiskLevelEnum{
	"low",
	"medium",
	"high",
	"unknown",
}

func (v *RiskLevelEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RiskLevelEnum(value)
	for _, existing := range AllowedRiskLevelEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RiskLevelEnum", value)
}

// NewRiskLevelEnumFromValue returns a pointer to a valid RiskLevelEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRiskLevelEnumFromValue(v string) (*RiskLevelEnum, error) {
	ev := RiskLevelEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RiskLevelEnum: valid values are %v", v, AllowedRiskLevelEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RiskLevelEnum) IsValid() bool {
	for _, existing := range AllowedRiskLevelEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RiskLevelEnum value
func (v RiskLevelEnum) Ptr() *RiskLevelEnum {
	return &v
}

type NullableRiskLevelEnum struct {
	value *RiskLevelEnum
	isSet bool
}

func (v NullableRiskLevelEnum) Get() *RiskLevelEnum {
	return v.value
}

func (v *NullableRiskLevelEnum) Set(val *RiskLevelEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskLevelEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskLevelEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskLevelEnum(val *RiskLevelEnum) *NullableRiskLevelEnum {
	return &NullableRiskLevelEnum{value: val, isSet: true}
}

func (v NullableRiskLevelEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskLevelEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

