/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://mailsafepro-api.fly.dev/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the APIKeyMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &APIKeyMeta{}

// APIKeyMeta API Key metadata
type APIKeyMeta struct {
	// Unique key identifier
	Id string `json:"id"`
	// Hashed key value
	KeyHash string `json:"key_hash"`
	// Associated plan
	Plan PlanEnum `json:"plan"`
	// Creation timestamp
	CreatedAt time.Time `json:"created_at"`
	// Revocation status
	Revoked bool `json:"revoked"`
	RevokedAt NullableTime `json:"revoked_at,omitempty"`
	// Access scopes
	Scopes []string `json:"scopes,omitempty"`
	Name NullableString `json:"name,omitempty"`
	LastUsed NullableTime `json:"last_used,omitempty"`
}

type _APIKeyMeta APIKeyMeta

// NewAPIKeyMeta instantiates a new APIKeyMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIKeyMeta(id string, keyHash string, plan PlanEnum, createdAt time.Time, revoked bool) *APIKeyMeta {
	this := APIKeyMeta{}
	this.Id = id
	this.KeyHash = keyHash
	this.Plan = plan
	this.CreatedAt = createdAt
	this.Revoked = revoked
	return &this
}

// NewAPIKeyMetaWithDefaults instantiates a new APIKeyMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIKeyMetaWithDefaults() *APIKeyMeta {
	this := APIKeyMeta{}
	return &this
}

// GetId returns the Id field value
func (o *APIKeyMeta) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *APIKeyMeta) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *APIKeyMeta) SetId(v string) {
	o.Id = v
}

// GetKeyHash returns the KeyHash field value
func (o *APIKeyMeta) GetKeyHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.KeyHash
}

// GetKeyHashOk returns a tuple with the KeyHash field value
// and a boolean to check if the value has been set.
func (o *APIKeyMeta) GetKeyHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeyHash, true
}

// SetKeyHash sets field value
func (o *APIKeyMeta) SetKeyHash(v string) {
	o.KeyHash = v
}

// GetPlan returns the Plan field value
func (o *APIKeyMeta) GetPlan() PlanEnum {
	if o == nil {
		var ret PlanEnum
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *APIKeyMeta) GetPlanOk() (*PlanEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *APIKeyMeta) SetPlan(v PlanEnum) {
	o.Plan = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *APIKeyMeta) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *APIKeyMeta) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *APIKeyMeta) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetRevoked returns the Revoked field value
func (o *APIKeyMeta) GetRevoked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Revoked
}

// GetRevokedOk returns a tuple with the Revoked field value
// and a boolean to check if the value has been set.
func (o *APIKeyMeta) GetRevokedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revoked, true
}

// SetRevoked sets field value
func (o *APIKeyMeta) SetRevoked(v bool) {
	o.Revoked = v
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *APIKeyMeta) GetRevokedAt() time.Time {
	if o == nil || IsNil(o.RevokedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.RevokedAt.Get()
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *APIKeyMeta) GetRevokedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RevokedAt.Get(), o.RevokedAt.IsSet()
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *APIKeyMeta) HasRevokedAt() bool {
	if o != nil && o.RevokedAt.IsSet() {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given NullableTime and assigns it to the RevokedAt field.
func (o *APIKeyMeta) SetRevokedAt(v time.Time) {
	o.RevokedAt.Set(&v)
}
// SetRevokedAtNil sets the value for RevokedAt to be an explicit nil
func (o *APIKeyMeta) SetRevokedAtNil() {
	o.RevokedAt.Set(nil)
}

// UnsetRevokedAt ensures that no value is present for RevokedAt, not even an explicit nil
func (o *APIKeyMeta) UnsetRevokedAt() {
	o.RevokedAt.Unset()
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *APIKeyMeta) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIKeyMeta) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *APIKeyMeta) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *APIKeyMeta) SetScopes(v []string) {
	o.Scopes = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *APIKeyMeta) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *APIKeyMeta) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *APIKeyMeta) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *APIKeyMeta) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *APIKeyMeta) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *APIKeyMeta) UnsetName() {
	o.Name.Unset()
}

// GetLastUsed returns the LastUsed field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *APIKeyMeta) GetLastUsed() time.Time {
	if o == nil || IsNil(o.LastUsed.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastUsed.Get()
}

// GetLastUsedOk returns a tuple with the LastUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *APIKeyMeta) GetLastUsedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUsed.Get(), o.LastUsed.IsSet()
}

// HasLastUsed returns a boolean if a field has been set.
func (o *APIKeyMeta) HasLastUsed() bool {
	if o != nil && o.LastUsed.IsSet() {
		return true
	}

	return false
}

// SetLastUsed gets a reference to the given NullableTime and assigns it to the LastUsed field.
func (o *APIKeyMeta) SetLastUsed(v time.Time) {
	o.LastUsed.Set(&v)
}
// SetLastUsedNil sets the value for LastUsed to be an explicit nil
func (o *APIKeyMeta) SetLastUsedNil() {
	o.LastUsed.Set(nil)
}

// UnsetLastUsed ensures that no value is present for LastUsed, not even an explicit nil
func (o *APIKeyMeta) UnsetLastUsed() {
	o.LastUsed.Unset()
}

func (o APIKeyMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o APIKeyMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["key_hash"] = o.KeyHash
	toSerialize["plan"] = o.Plan
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["revoked"] = o.Revoked
	if o.RevokedAt.IsSet() {
		toSerialize["revoked_at"] = o.RevokedAt.Get()
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.LastUsed.IsSet() {
		toSerialize["last_used"] = o.LastUsed.Get()
	}
	return toSerialize, nil
}

func (o *APIKeyMeta) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"key_hash",
		"plan",
		"created_at",
		"revoked",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAPIKeyMeta := _APIKeyMeta{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAPIKeyMeta)

	if err != nil {
		return err
	}

	*o = APIKeyMeta(varAPIKeyMeta)

	return err
}

type NullableAPIKeyMeta struct {
	value *APIKeyMeta
	isSet bool
}

func (v NullableAPIKeyMeta) Get() *APIKeyMeta {
	return v.value
}

func (v *NullableAPIKeyMeta) Set(val *APIKeyMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIKeyMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIKeyMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIKeyMeta(val *APIKeyMeta) *NullableAPIKeyMeta {
	return &NullableAPIKeyMeta{value: val, isSet: true}
}

func (v NullableAPIKeyMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIKeyMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


