/*
Email Validation API — Enterprise-grade Email Verification

API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://api.mailsafepro.es/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

API version: 2.5.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mailsafepro

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchEmailResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchEmailResponse{}

// BatchEmailResponse Batch validation response
type BatchEmailResponse struct {
	// Total emails processed
	Count int32 `json:"count"`
	// Number of valid emails
	ValidCount int32 `json:"valid_count"`
	// Number of invalid emails
	InvalidCount int32 `json:"invalid_count"`
	// Total processing time in seconds
	ProcessingTime float32 `json:"processing_time"`
	// Average processing time per email
	AverageTime float32 `json:"average_time"`
	// Individual validation results
	Results []EmailResponse `json:"results"`
}

type _BatchEmailResponse BatchEmailResponse

// NewBatchEmailResponse instantiates a new BatchEmailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchEmailResponse(count int32, validCount int32, invalidCount int32, processingTime float32, averageTime float32, results []EmailResponse) *BatchEmailResponse {
	this := BatchEmailResponse{}
	this.Count = count
	this.ValidCount = validCount
	this.InvalidCount = invalidCount
	this.ProcessingTime = processingTime
	this.AverageTime = averageTime
	this.Results = results
	return &this
}

// NewBatchEmailResponseWithDefaults instantiates a new BatchEmailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchEmailResponseWithDefaults() *BatchEmailResponse {
	this := BatchEmailResponse{}
	return &this
}

// GetCount returns the Count field value
func (o *BatchEmailResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *BatchEmailResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *BatchEmailResponse) SetCount(v int32) {
	o.Count = v
}

// GetValidCount returns the ValidCount field value
func (o *BatchEmailResponse) GetValidCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ValidCount
}

// GetValidCountOk returns a tuple with the ValidCount field value
// and a boolean to check if the value has been set.
func (o *BatchEmailResponse) GetValidCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidCount, true
}

// SetValidCount sets field value
func (o *BatchEmailResponse) SetValidCount(v int32) {
	o.ValidCount = v
}

// GetInvalidCount returns the InvalidCount field value
func (o *BatchEmailResponse) GetInvalidCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InvalidCount
}

// GetInvalidCountOk returns a tuple with the InvalidCount field value
// and a boolean to check if the value has been set.
func (o *BatchEmailResponse) GetInvalidCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvalidCount, true
}

// SetInvalidCount sets field value
func (o *BatchEmailResponse) SetInvalidCount(v int32) {
	o.InvalidCount = v
}

// GetProcessingTime returns the ProcessingTime field value
func (o *BatchEmailResponse) GetProcessingTime() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ProcessingTime
}

// GetProcessingTimeOk returns a tuple with the ProcessingTime field value
// and a boolean to check if the value has been set.
func (o *BatchEmailResponse) GetProcessingTimeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProcessingTime, true
}

// SetProcessingTime sets field value
func (o *BatchEmailResponse) SetProcessingTime(v float32) {
	o.ProcessingTime = v
}

// GetAverageTime returns the AverageTime field value
func (o *BatchEmailResponse) GetAverageTime() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AverageTime
}

// GetAverageTimeOk returns a tuple with the AverageTime field value
// and a boolean to check if the value has been set.
func (o *BatchEmailResponse) GetAverageTimeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AverageTime, true
}

// SetAverageTime sets field value
func (o *BatchEmailResponse) SetAverageTime(v float32) {
	o.AverageTime = v
}

// GetResults returns the Results field value
func (o *BatchEmailResponse) GetResults() []EmailResponse {
	if o == nil {
		var ret []EmailResponse
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *BatchEmailResponse) GetResultsOk() ([]EmailResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *BatchEmailResponse) SetResults(v []EmailResponse) {
	o.Results = v
}

func (o BatchEmailResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchEmailResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["valid_count"] = o.ValidCount
	toSerialize["invalid_count"] = o.InvalidCount
	toSerialize["processing_time"] = o.ProcessingTime
	toSerialize["average_time"] = o.AverageTime
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

func (o *BatchEmailResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"valid_count",
		"invalid_count",
		"processing_time",
		"average_time",
		"results",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchEmailResponse := _BatchEmailResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchEmailResponse)

	if err != nil {
		return err
	}

	*o = BatchEmailResponse(varBatchEmailResponse)

	return err
}

type NullableBatchEmailResponse struct {
	value *BatchEmailResponse
	isSet bool
}

func (v NullableBatchEmailResponse) Get() *BatchEmailResponse {
	return v.value
}

func (v *NullableBatchEmailResponse) Set(val *BatchEmailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchEmailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchEmailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchEmailResponse(val *BatchEmailResponse) *NullableBatchEmailResponse {
	return &NullableBatchEmailResponse{value: val, isSet: true}
}

func (v NullableBatchEmailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchEmailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


